# ===========================================================================
# [交接導向註解]
# 腳本：建立 Vivado 工程、加入 cfg_hub。流程：SoC。
# ===========================================================================

create_project finn_vivado_stitch_proj ${MARS_ROOT}/thesis/finn/finn_pipeline/vivado_stitch_proj_hv26s5y4 -part xc7z020clg400-1
set_msg_config -id {[BD 41-1753]} -suppress
set_property ip_repo_paths [list $::env(FINN_ROOT)/finn-rtllib/memstream ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_rtl_0_99qzhk6p ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0_4owmbjtx ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_i9afw0fi ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_0_qnbctnd9 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_0_swwld609/project_StreamingDataflowPartition_1_MVAU_hls_0/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1_hnj9wz0b ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1__hx6nwq1 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_1_3tbjp50l ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_1_hhty516s/project_StreamingDataflowPartition_1_MVAU_hls_1/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2_kw9a1cd9 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingMaxPool_hls_0_p2wknr6f/project_StreamingDataflowPartition_1_StreamingMaxPool_hls_0/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3_qwnruaue ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_octv5k_1 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_2_acy74ls1 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_2_qsg5tse5/project_StreamingDataflowPartition_1_MVAU_hls_2/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4_dsg5k044 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_45ch2i34 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_3_mbx1lk49 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_3_x8rx42tr/project_StreamingDataflowPartition_1_MVAU_hls_3/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5_r2to5w1_ ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingMaxPool_hls_1_rldan_qn/project_StreamingDataflowPartition_1_StreamingMaxPool_hls_1/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6_0mkmpd6x ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_4xjj_922 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_4_iixqhg8l ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_4_hzpkme6z/project_StreamingDataflowPartition_1_MVAU_hls_4/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7_sapp7gg0 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_foxk66jp ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_5_f5n7m2a3/project_StreamingDataflowPartition_1_MVAU_hls_5/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8_vchfsia9 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_6_wufh1rm2/project_StreamingDataflowPartition_1_MVAU_hls_6/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9_lxcmit07 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_5_mru2rdgc ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_7_shqcyqkc/project_StreamingDataflowPartition_1_MVAU_hls_7/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_6_2tha66r2 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_8_n0nyq7_y/project_StreamingDataflowPartition_1_MVAU_hls_8/sol1/impl/ip ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10_0irwzy50 ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_LabelSelect_hls_0_fvq8a7ow/project_StreamingDataflowPartition_1_LabelSelect_hls_0/sol1/impl/ip] [current_project]
update_ip_catalog
create_bd_design "StreamingDataflowPartition_1"
file mkdir ./ip/verilog/rtl_ops/StreamingDataflowPartition_1_Thresholding_rtl_0
add_files -copy_to ./ip/verilog/rtl_ops/StreamingDataflowPartition_1_Thresholding_rtl_0 -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_rtl_0_99qzhk6p/axilite_if.v
add_files -copy_to ./ip/verilog/rtl_ops/StreamingDataflowPartition_1_Thresholding_rtl_0 -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_rtl_0_99qzhk6p/thresholding.sv
add_files -copy_to ./ip/verilog/rtl_ops/StreamingDataflowPartition_1_Thresholding_rtl_0 -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_rtl_0_99qzhk6p/thresholding_axi.sv
add_files -copy_to ./ip/verilog/rtl_ops/StreamingDataflowPartition_1_Thresholding_rtl_0 -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_Thresholding_rtl_0_99qzhk6p/StreamingDataflowPartition_1_Thresholding_rtl_0_axi_wrapper.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_Thresholding_rtl_0_axi_wrapper StreamingDataflowPartition_1_Thresholding_rtl_0
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0_4owmbjtx/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0_4owmbjtx/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0_4owmbjtx/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_i9afw0fi/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_i9afw0fi/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_i9afw0fi/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0_i9afw0fi/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_0_qnbctnd9/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_0_qnbctnd9/StreamingDataflowPartition_1_StreamingFIFO_rtl_0.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_0 StreamingDataflowPartition_1_StreamingFIFO_rtl_0
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_0
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_0/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_0/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_0/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_0/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_0:1.0 /StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0_wstrm
set_property -dict [list CONFIG.DEPTH {36} CONFIG.WIDTH {48} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_0_swwld609/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/StreamingDataflowPartition_1_MVAU_hls_0/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1_hnj9wz0b/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1_hnj9wz0b/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1_hnj9wz0b/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1__hx6nwq1/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1__hx6nwq1/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1__hx6nwq1/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1__hx6nwq1/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_1_3tbjp50l/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_1_3tbjp50l/StreamingDataflowPartition_1_StreamingFIFO_rtl_1.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_1 StreamingDataflowPartition_1_StreamingFIFO_rtl_1
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_1
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_1/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_1/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_1/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_1:1.0 /StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1_wstrm
set_property -dict [list CONFIG.DEPTH {36} CONFIG.WIDTH {1024} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_1_hhty516s/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/StreamingDataflowPartition_1_MVAU_hls_1/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2_kw9a1cd9/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2_kw9a1cd9/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2_kw9a1cd9/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingMaxPool_hls_0:1.0 StreamingDataflowPartition_1_StreamingMaxPool_hls_0
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3_qwnruaue/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3_qwnruaue/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3_qwnruaue/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_octv5k_1/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_octv5k_1/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_octv5k_1/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2_octv5k_1/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_2_acy74ls1/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_2_acy74ls1/StreamingDataflowPartition_1_StreamingFIFO_rtl_2.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_2 StreamingDataflowPartition_1_StreamingFIFO_rtl_2
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_2
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_2/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_2/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_2/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_2/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_2:1.0 /StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2_wstrm
set_property -dict [list CONFIG.DEPTH {144} CONFIG.WIDTH {512} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_2_qsg5tse5/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/StreamingDataflowPartition_1_MVAU_hls_2/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4_dsg5k044/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4_dsg5k044/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4_dsg5k044/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_45ch2i34/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_45ch2i34/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_45ch2i34/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3_45ch2i34/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_3_mbx1lk49/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_3_mbx1lk49/StreamingDataflowPartition_1_StreamingFIFO_rtl_3.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_3 StreamingDataflowPartition_1_StreamingFIFO_rtl_3
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_3
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_3/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_3/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_3/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_3:1.0 /StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3_wstrm
set_property -dict [list CONFIG.DEPTH {288} CONFIG.WIDTH {512} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_3_x8rx42tr/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/StreamingDataflowPartition_1_MVAU_hls_3/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5_r2to5w1_/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5_r2to5w1_/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5_r2to5w1_/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingMaxPool_hls_1:1.0 StreamingDataflowPartition_1_StreamingMaxPool_hls_1
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6_0mkmpd6x/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6_0mkmpd6x/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6_0mkmpd6x/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_4xjj_922/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_4xjj_922/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_4xjj_922/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4_4xjj_922/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_4_iixqhg8l/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_4_iixqhg8l/StreamingDataflowPartition_1_StreamingFIFO_rtl_4.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_4 StreamingDataflowPartition_1_StreamingFIFO_rtl_4
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_4
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_4/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_4/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_4/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_4/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_4:1.0 /StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4_wstrm
set_property -dict [list CONFIG.DEPTH {2304} CONFIG.WIDTH {128} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_4_hzpkme6z/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/StreamingDataflowPartition_1_MVAU_hls_4/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7_sapp7gg0/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7_sapp7gg0/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7_sapp7gg0/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_foxk66jp/swg_pkg.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_foxk66jp/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_wrapper.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_foxk66jp/StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_impl.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5_foxk66jp/swg_common.sv
create_bd_cell -type module -reference StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5 StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_5
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_5/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_5/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_5/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_5/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_5:1.0 /StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5_wstrm
set_property -dict [list CONFIG.DEPTH {18432} CONFIG.WIDTH {32} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_5_f5n7m2a3/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/StreamingDataflowPartition_1_MVAU_hls_5/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8_vchfsia9/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8_vchfsia9/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8_vchfsia9/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_6
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_6/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_6/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_6/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_6/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_6:1.0 /StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6_wstrm
set_property -dict [list CONFIG.DEPTH {32768} CONFIG.WIDTH {8} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_6_wufh1rm2/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/StreamingDataflowPartition_1_MVAU_hls_6/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9_lxcmit07/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9_lxcmit07/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9_lxcmit07/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_5_mru2rdgc/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_5_mru2rdgc/StreamingDataflowPartition_1_StreamingFIFO_rtl_5.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_5 StreamingDataflowPartition_1_StreamingFIFO_rtl_5
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_7
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_7/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_7/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_7/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_7:1.0 /StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7_wstrm
set_property -dict [list CONFIG.DEPTH {32768} CONFIG.WIDTH {8} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_7_shqcyqkc/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/StreamingDataflowPartition_1_MVAU_hls_7/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_6_2tha66r2/Q_srl.v
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_rtl_6_2tha66r2/StreamingDataflowPartition_1_StreamingFIFO_rtl_6.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingFIFO_rtl_6 StreamingDataflowPartition_1_StreamingFIFO_rtl_6
create_bd_cell -type hier StreamingDataflowPartition_1_MVAU_hls_8
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_MVAU_hls_8/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_MVAU_hls_8/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_8/out_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_MVAU_hls_8/in0_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_MVAU_hls_8:1.0 /StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8
create_bd_cell -type ip -vlnv amd.com:finn:memstream:1.0 /StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8_wstrm
set_property -dict [list CONFIG.DEPTH {1024} CONFIG.WIDTH {8} CONFIG.INIT_FILE {${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_8_n0nyq7_y/memblock.dat} CONFIG.RAM_STYLE {auto} ] [get_bd_cells /StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8/weights_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8_wstrm/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8_wstrm/ap_clk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/in0_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8/in0_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/StreamingDataflowPartition_1_MVAU_hls_8/out_V]
save_bd_design
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10_0irwzy50/dwc_axi.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10_0irwzy50/dwc.sv
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/code_gen_ipgen_StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10_0irwzy50/StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10.v
create_bd_cell -type module -reference StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10 StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_LabelSelect_hls_0:1.0 StreamingDataflowPartition_1_LabelSelect_hls_0
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_Thresholding_rtl_0/ap_clk]
set_property name ap_clk [get_bd_ports ap_clk_0]
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_Thresholding_rtl_0/ap_rst_n]
set_property name ap_rst_n [get_bd_ports ap_rst_n_0]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_rtl_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_2/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_0/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_0/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_3/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_2/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_2/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_2/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_4/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_3/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_3/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_3/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_5/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_1/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_hls_1/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_6/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_4/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_4/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_4/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_7/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_rtl_5/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_5/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_8/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_6/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_9/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_5/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_5/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_7/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_6/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_MVAU_hls_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_rtl_6/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_MVAU_hls_8/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10/in0_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_hls_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_hls_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_rtl_10/out_V] [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_hls_0/in0_V]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_rtl_0/in0_V]
set_property name s_axis_0 [get_bd_intf_ports in0_V_0]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_hls_0/out_V]
set_property name m_axis_0 [get_bd_intf_ports out_V_0]
set_property CONFIG.FREQ_HZ 100000000 [get_bd_ports /ap_clk]
validate_bd_design
save_bd_design
make_wrapper -files [get_files ${MARS_ROOT}/thesis/finn/finn_pipeline/vivado_stitch_proj_hv26s5y4/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/StreamingDataflowPartition_1.bd] -top
add_files -norecurse ${MARS_ROOT}/thesis/finn/finn_pipeline/vivado_stitch_proj_hv26s5y4/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/hdl/StreamingDataflowPartition_1_wrapper.v
set_property top StreamingDataflowPartition_1_wrapper [current_fileset]
ipx::package_project -root_dir ${MARS_ROOT}/thesis/finn/finn_pipeline/vivado_stitch_proj_hv26s5y4/ip -vendor xilinx_finn -library finn -taxonomy /UserIP -module StreamingDataflowPartition_1 -import_files
set_property ipi_drc {ignore_freq_hz true} [ipx::current_core]
ipx::remove_segment -quiet m_axi_gmem0:APERTURE_0 [ipx::get_address_spaces m_axi_gmem0 -of_objects [ipx::current_core]]
set_property core_revision 2 [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::create_xgui_files [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property value_resolve_type user [ipx::get_bus_parameters -of [ipx::get_bus_interfaces -of [ipx::current_core ]]]

set core [ipx::current_core]

# Add rudimentary driver
file copy -force data ip/
set file_group [ipx::add_file_group -type software_driver {} $core]
set_property type mdd       [ipx::add_file data/finn_design.mdd $file_group]
set_property type tclSource [ipx::add_file data/finn_design.tcl $file_group]

# Remove all XCI references to subcores
set impl_files [ipx::get_file_groups xilinx_implementation -of $core]
foreach xci [ipx::get_files -of $impl_files {*.xci}] {
    ipx::remove_file [get_property NAME $xci] $impl_files
}

# Construct a single flat memory map for each AXI-lite interface port
foreach port [get_bd_intf_ports -filter {CONFIG.PROTOCOL==AXI4LITE}] {
    set pin $port
    set awidth ""
    while { $awidth == "" } {
        set pins [get_bd_intf_pins -of [get_bd_intf_nets -boundary_type lower -of $pin]]
        set kill [lsearch $pins $pin]
        if { $kill >= 0 } { set pins [lreplace $pins $kill $kill] }
        if { [llength $pins] != 1 } { break }
        set pin [lindex $pins 0]
        set awidth [get_property CONFIG.ADDR_WIDTH $pin]
    }
    if { $awidth == "" } {
       puts "CRITICAL WARNING: Unable to construct address map for $port."
    } {
       set range [expr 2**$awidth]
       set range [expr $range < 4096 ? 4096 : $range]
       puts "INFO: Building address map for $port: 0+:$range"
       set name [get_property NAME $port]
       set addr_block [ipx::add_address_block Reg0 [ipx::add_memory_map $name $core]]
       set_property range $range $addr_block
       set_property slave_memory_map_ref $name [ipx::get_bus_interfaces $name -of $core]
    }
}

# Finalize and Save
ipx::update_checksums $core
ipx::save_core $core

# Remove stale subcore references from component.xml
file rename -force ip/component.xml ip/component.bak
set ifile [open ip/component.bak r]
set ofile [open ip/component.xml w]
set buf [list]
set kill 0
while { [eof $ifile] != 1 } {
    gets $ifile line
    if { [string match {*<spirit:fileSet>*} $line] == 1 } {
        foreach l $buf { puts $ofile $l }
        set buf [list $line]
    } elseif { [llength $buf] > 0 } {
        lappend buf $line

        if { [string match {*</spirit:fileSet>*} $line] == 1 } {
            if { $kill == 0 } { foreach l $buf { puts $ofile $l } }
            set buf [list]
            set kill 0
        } elseif { [string match {*<xilinx:subCoreRef>*} $line] == 1 } {
            set kill 1
        }
    } else {
        puts $ofile $line
    }
}
close $ifile
close $ofile

set all_v_files [get_files -filter {USED_IN_SYNTHESIS == 1 && (FILE_TYPE == Verilog || FILE_TYPE == SystemVerilog || FILE_TYPE =="Verilog Header")}]
set fp [open ${MARS_ROOT}/thesis/finn/finn_pipeline/vivado_stitch_proj_hv26s5y4/all_verilog_srcs.txt w]
foreach vf $all_v_files {puts $fp $vf}
close $fp
