`timescale 1ns / 1ps

// MVAU2_Super_Wrapper — multi-branch M=1 (compact), generated by
// gen_multibranch_rtl.py. Ports identical to the M=1 wrapper.
module MVAU2_Super_Wrapper (
    input  wire        ap_clk,
    input  wire        ap_rst_n,

    input  wire [31:0] in0_V_TDATA,
    input  wire        in0_V_TVALID,
    output wire        in0_V_TREADY,

    input  wire [31:0] weights_V_TDATA,
    input  wire        weights_V_TVALID,
    output wire        weights_V_TREADY,

    output wire [7:0]  out_V_TDATA,
    output wire        out_V_TVALID,
    input  wire        out_V_TREADY,

    // Runtime config write port (from adapter_cfg_hub)
    input  wire [10:0] cfg_waddr,
    input  wire [31:0] cfg_wdata,
    input  wire        cfg_wen
);

    // word 0: adapter_enable, word 1: branch_sel (new for multi-branch)
    reg        adapter_enable;
    reg [1:0]  branch_sel;
    always @(posedge ap_clk) begin
        if (!ap_rst_n) begin
            adapter_enable <= 1'b1;
            branch_sel     <= 2'd0;
        end else if (cfg_wen) begin
            if (cfg_waddr == 11'd0) adapter_enable <= cfg_wdata[0];
            if (cfg_waddr == 11'd1) branch_sel     <= cfg_wdata[1:0];
        end
    end

    // ---- broadcast in0 to MVAU + all branches (all-ready fork, same
    //      semantics as the M=1 Stream_Splitter) ----
    wire mvau_in_ready;
    wire br_in_ready_b0;
    assign in0_V_TREADY = mvau_in_ready && br_in_ready_b0;
    wire bcast_valid = in0_V_TVALID && in0_V_TREADY;

    wire [31:0] mvau_to_add_tdata;
    wire mvau_to_add_tvalid, mvau_to_add_tready;

    StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_2_0 mvau_inst (
        .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),
        .in0_V_TVALID(bcast_valid), .in0_V_TREADY(mvau_in_ready), .in0_V_TDATA(in0_V_TDATA),
        .weights_V_TVALID(weights_V_TVALID), .weights_V_TREADY(weights_V_TREADY), .weights_V_TDATA(weights_V_TDATA),
        .out_V_TVALID(mvau_to_add_tvalid), .out_V_TREADY(mvau_to_add_tready), .out_V_TDATA(mvau_to_add_tdata)
    );

    // ------------------ branch 0 ------------------
    wire [7:0] adapt_to_fifo_tdata_b0, fifo_to_add_tdata_b0;
    wire adapt_to_fifo_tvalid_b0, adapt_to_fifo_tready_b0;
    wire fifo_to_add_tvalid_b0, fifo_to_add_tready_b0;
    wire cfg_wen_b0 = cfg_wen && (branch_sel == 2'd0);

    Adapter_MVAU2 adapter_inst_b0 (
        .aclk(ap_clk), .aresetn(ap_rst_n),
        .s_axis_tdata(in0_V_TDATA), .s_axis_tvalid(bcast_valid), .s_axis_tready(br_in_ready_b0),
        .m_axis_tdata(adapt_to_fifo_tdata_b0), .m_axis_tvalid(adapt_to_fifo_tvalid_b0), .m_axis_tready(adapt_to_fifo_tready_b0),
        .cfg_waddr(cfg_waddr), .cfg_wdata(cfg_wdata), .cfg_wen(cfg_wen_b0)
    );

    Simple_FIFO_mvau2 #(.WIDTH(8), .DEPTH_LOG2(4)) fifo_inst_b0 (
        .clk(ap_clk), .rst_n(ap_rst_n),
        .s_axis_tdata(adapt_to_fifo_tdata_b0), .s_axis_tvalid(adapt_to_fifo_tvalid_b0), .s_axis_tready(adapt_to_fifo_tready_b0),
        .m_axis_tdata(fifo_to_add_tdata_b0), .m_axis_tvalid(fifo_to_add_tvalid_b0), .m_axis_tready(fifo_to_add_tready_b0)
    );

    wire adder_out_bit;
    assign out_V_TDATA = {7'b0, adder_out_bit};
    Stream_Adder_Threshold_mvau2 adder_thresh_inst (
        .aclk(ap_clk), .aresetn(ap_rst_n),
        .s_axis_1_tdata(mvau_to_add_tdata), .s_axis_1_tvalid(mvau_to_add_tvalid), .s_axis_1_tready(mvau_to_add_tready),
        .s_axis_2_b0_tdata(fifo_to_add_tdata_b0), .s_axis_2_b0_tvalid(fifo_to_add_tvalid_b0), .s_axis_2_b0_tready(fifo_to_add_tready_b0),
        .m_axis_tdata(adder_out_bit), .m_axis_tvalid(out_V_TVALID), .m_axis_tready(out_V_TREADY),
        .cfg_waddr(cfg_waddr), .cfg_wdata(cfg_wdata), .cfg_wen(cfg_wen), .branch_sel(branch_sel),
        .adapter_enable(adapter_enable)
    );

endmodule
