// ===========================================================================
// [交接導向註解]
// 模組：MVAU1 加法+Q8閾值。用 contribution LUT 縮放 Adapter popcount，與 MVAU partial-sum 相加後二值化（零 DSP）。流程：RTL。
// ===========================================================================

`timescale 1ns / 1ps

// =====================================================================
// MVAU1 Stream_Adder_Threshold (adapter_fixed, Q8-widened)
// =====================================================================
// 2026-04-11 design notes (do NOT patch .dat files to chase off-by-ones
// — fix this RTL / regenerate the helper .dat from sw/ instead):
//
//   * memblock.dat, mvau1_in.dat, golden adapter weight .dat files are
//     FINN / helper truth. Do not patch them.
//   * Per-PE Q8 threshold + adapter-sign + alpha ROMs are regenerated by
//     sw/make_mvau1_q8_assets.py from the SAME RC_m1_full.tar used by
//     sw/pytorch_forward_mvau1.py, so they encode PyTorch ground truth.
//
// FINN BN absorption caveat:
//   When FINN runs batchnorm_to_multithreshold on bn1, channels whose
//   BN gamma is negative have their sign folded into the PRECEDING conv
//   weights that ship inside memblock.dat. For MVAU1 that's 9 channels
//   ([1,14,21,24,31,37,44,45,52]) whose FINN MVAU popcount P satisfies
//     2*P - K  =  -x_pyt     (inverted vs PyTorch bipolar dot)
//   The adapter-side up/down/rc weights are NOT BN-folded — they match
//   PyTorch sign convention for all 64 channels. So the RTL has to add
//   the adapter contribution for gamma>0 channels and SUBTRACT it for
//   gamma<0 channels in order to stay PyTorch-equivalent.
//
// Datapath (Q8 popcount domain, exact integer):
//
//   contrib    = (adp_pop - 24) * ALPHA_Q8          // no rounding
//   signed_c   = adp_sign ? -contrib : contrib      // per-channel flip
//   RTL_lhs_q8 = (s1_mvau_pop <<< 8) + signed_c
//   result_bit = RTL_lhs_q8 >= thresh_q8[ch]        // unified >=
//
//   Threshold encoding (signed Q8, stored per (PE, step)):
//     gamma > 0 (adp_sign = 0):  T = ceil(128 * (K + t_bip_float))
//     gamma < 0 (adp_sign = 1):  T = ceil(128 * (K - t_bip_float))
//     K = 64 * 9 = 576.
//
//   LUT rationale (unchanged — offset 24 compensates for the HIDDEN=16
//   zero-extension in Adapter_MVAU1's 32-bit XNOR):
//     adp_pop      = 16 + real_match
//     bipolar_dot  = 2*real_match - 16 = 2*(adp_pop - 24)
//     popcount-domain contribution = (alpha/2)*bipolar_dot
//                                  = (adp_pop - 24)*alpha
//     Stored as Q8: (adp_pop - 24) * ALPHA_Q8  (exact).
//
//   PE/step → channel mapping (unchanged from prior rev):
//     thresh_rom_p[s] / adp_sign_rom_p[s] correspond to ch = s*32 + p
//     (s = step_cnt, p = PE idx)
// =====================================================================

// Override at xelab time, e.g.:
//   -d "MVAU1_THRESH_DIR=\"D:/path/to/new_app/data\""
//   -d "MVAU1_ALPHA_Q8_FILE=\"D:/path/to/new_app/data/mvau1_alpha_q8.dat\""
`ifndef MVAU1_THRESH_DIR
  `define MVAU1_THRESH_DIR "/home/barkie1/mvau_pipeline/mvau_adapter/mvau1/data"
`endif
`ifndef MVAU1_CONTRIB_LUT_FILE
  `define MVAU1_CONTRIB_LUT_FILE "/home/barkie1/mvau_pipeline/mvau_adapter/mvau1/data/mvau1_contrib_lut.dat"
`endif

module Stream_Adder_Threshold_mvau1 (
    input  wire                  aclk,
    input  wire                  aresetn,

    input  wire [1023:0]         s_axis_1_tdata,
    input  wire                  s_axis_1_tvalid,
    output wire                  s_axis_1_tready,

    input  wire [255:0]          s_axis_2_tdata,
    input  wire                  s_axis_2_tvalid,
    output wire                  s_axis_2_tready,

    output reg  [31:0]           m_axis_tdata,
    output reg                   m_axis_tvalid,
    input  wire                  m_axis_tready
);

    // LUT (adp_contrib_lut) is precomputed in software (sw/make_adp_contrib_luts.py)
    // and loaded below via $readmemh. Vivado synth refuses to fold a register-backed
    // multiply inside an initial-block for loop, so we must hand it the final table.
    parameter PE = 32;

    // =========================================================
    // Threshold ROM (32 files, 2 entries each, signed Q8)
    // Polarity ROM (32 files, 2 entries each, 1-bit)
    // =========================================================
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_0  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_1  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_2  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_3  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_4  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_5  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_6  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_7  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_8  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_9  [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_10 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_11 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_12 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_13 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_14 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_15 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_16 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_17 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_18 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_19 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_20 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_21 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_22 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_23 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_24 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_25 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_26 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_27 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_28 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_29 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_30 [0:1];
    (* rom_style = "distributed" *) reg signed [31:0] thresh_rom_31 [0:1];

    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_0  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_1  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_2  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_3  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_4  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_5  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_6  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_7  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_8  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_9  [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_10 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_11 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_12 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_13 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_14 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_15 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_16 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_17 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_18 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_19 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_20 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_21 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_22 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_23 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_24 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_25 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_26 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_27 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_28 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_29 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_30 [0:1];
    (* rom_style = "distributed" *) reg [7:0] adp_sign_rom_31 [0:1];

    initial begin
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_0_q8.dat"},  thresh_rom_0);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_1_q8.dat"},  thresh_rom_1);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_2_q8.dat"},  thresh_rom_2);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_3_q8.dat"},  thresh_rom_3);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_4_q8.dat"},  thresh_rom_4);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_5_q8.dat"},  thresh_rom_5);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_6_q8.dat"},  thresh_rom_6);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_7_q8.dat"},  thresh_rom_7);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_8_q8.dat"},  thresh_rom_8);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_9_q8.dat"},  thresh_rom_9);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_10_q8.dat"}, thresh_rom_10);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_11_q8.dat"}, thresh_rom_11);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_12_q8.dat"}, thresh_rom_12);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_13_q8.dat"}, thresh_rom_13);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_14_q8.dat"}, thresh_rom_14);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_15_q8.dat"}, thresh_rom_15);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_16_q8.dat"}, thresh_rom_16);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_17_q8.dat"}, thresh_rom_17);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_18_q8.dat"}, thresh_rom_18);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_19_q8.dat"}, thresh_rom_19);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_20_q8.dat"}, thresh_rom_20);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_21_q8.dat"}, thresh_rom_21);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_22_q8.dat"}, thresh_rom_22);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_23_q8.dat"}, thresh_rom_23);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_24_q8.dat"}, thresh_rom_24);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_25_q8.dat"}, thresh_rom_25);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_26_q8.dat"}, thresh_rom_26);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_27_q8.dat"}, thresh_rom_27);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_28_q8.dat"}, thresh_rom_28);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_29_q8.dat"}, thresh_rom_29);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_30_q8.dat"}, thresh_rom_30);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_thresh_31_q8.dat"}, thresh_rom_31);

        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_0.dat"},  adp_sign_rom_0);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_1.dat"},  adp_sign_rom_1);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_2.dat"},  adp_sign_rom_2);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_3.dat"},  adp_sign_rom_3);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_4.dat"},  adp_sign_rom_4);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_5.dat"},  adp_sign_rom_5);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_6.dat"},  adp_sign_rom_6);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_7.dat"},  adp_sign_rom_7);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_8.dat"},  adp_sign_rom_8);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_9.dat"},  adp_sign_rom_9);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_10.dat"}, adp_sign_rom_10);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_11.dat"}, adp_sign_rom_11);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_12.dat"}, adp_sign_rom_12);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_13.dat"}, adp_sign_rom_13);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_14.dat"}, adp_sign_rom_14);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_15.dat"}, adp_sign_rom_15);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_16.dat"}, adp_sign_rom_16);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_17.dat"}, adp_sign_rom_17);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_18.dat"}, adp_sign_rom_18);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_19.dat"}, adp_sign_rom_19);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_20.dat"}, adp_sign_rom_20);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_21.dat"}, adp_sign_rom_21);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_22.dat"}, adp_sign_rom_22);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_23.dat"}, adp_sign_rom_23);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_24.dat"}, adp_sign_rom_24);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_25.dat"}, adp_sign_rom_25);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_26.dat"}, adp_sign_rom_26);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_27.dat"}, adp_sign_rom_27);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_28.dat"}, adp_sign_rom_28);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_29.dat"}, adp_sign_rom_29);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_30.dat"}, adp_sign_rom_30);
        $readmemh({`MVAU1_THRESH_DIR, "/mvau1_adp_sign_31.dat"}, adp_sign_rom_31);
    end

    // =========================================================
    // Adapter LUT (exact Q8, offset 24 — see header note)
    //   adp_contrib_lut[i] = (i - 24) * ALPHA_Q8   (precomputed in software)
    // =========================================================
    (* rom_style = "distributed" *) reg signed [31:0] adp_contrib_lut [0:255];

    initial begin
        $readmemh(`MVAU1_CONTRIB_LUT_FILE, adp_contrib_lut);
    end

    // =========================================================
    // Pipeline signals
    // =========================================================
    reg [2:0] step_cnt;

    reg                    s1_valid;
    reg signed [31:0]      s1_mvau_pop     [0:PE-1];
    reg signed [31:0]      s1_adp_contrib  [0:PE-1];
    reg signed [31:0]      s1_threshold    [0:PE-1];
    reg                    s1_adp_sign     [0:PE-1];

    reg                    s2_valid;
    reg signed [31:0]      s2_total_pop_q8 [0:PE-1];
    reg signed [31:0]      s2_threshold    [0:PE-1];

    wire stall;
    wire in_fire;

    assign stall = m_axis_tvalid && !m_axis_tready;
    assign s_axis_1_tready = !stall && s_axis_2_tvalid;
    assign s_axis_2_tready = !stall && s_axis_1_tvalid;
    assign in_fire = s_axis_1_tvalid && s_axis_2_tvalid && !stall;

    // Threshold + pol wires
    wire signed [31:0] th_wire  [0:PE-1];
    wire               adp_sign_wire [0:PE-1];
    assign th_wire[0]  = thresh_rom_0[step_cnt[0]];
    assign th_wire[1]  = thresh_rom_1[step_cnt[0]];
    assign th_wire[2]  = thresh_rom_2[step_cnt[0]];
    assign th_wire[3]  = thresh_rom_3[step_cnt[0]];
    assign th_wire[4]  = thresh_rom_4[step_cnt[0]];
    assign th_wire[5]  = thresh_rom_5[step_cnt[0]];
    assign th_wire[6]  = thresh_rom_6[step_cnt[0]];
    assign th_wire[7]  = thresh_rom_7[step_cnt[0]];
    assign th_wire[8]  = thresh_rom_8[step_cnt[0]];
    assign th_wire[9]  = thresh_rom_9[step_cnt[0]];
    assign th_wire[10] = thresh_rom_10[step_cnt[0]];
    assign th_wire[11] = thresh_rom_11[step_cnt[0]];
    assign th_wire[12] = thresh_rom_12[step_cnt[0]];
    assign th_wire[13] = thresh_rom_13[step_cnt[0]];
    assign th_wire[14] = thresh_rom_14[step_cnt[0]];
    assign th_wire[15] = thresh_rom_15[step_cnt[0]];
    assign th_wire[16] = thresh_rom_16[step_cnt[0]];
    assign th_wire[17] = thresh_rom_17[step_cnt[0]];
    assign th_wire[18] = thresh_rom_18[step_cnt[0]];
    assign th_wire[19] = thresh_rom_19[step_cnt[0]];
    assign th_wire[20] = thresh_rom_20[step_cnt[0]];
    assign th_wire[21] = thresh_rom_21[step_cnt[0]];
    assign th_wire[22] = thresh_rom_22[step_cnt[0]];
    assign th_wire[23] = thresh_rom_23[step_cnt[0]];
    assign th_wire[24] = thresh_rom_24[step_cnt[0]];
    assign th_wire[25] = thresh_rom_25[step_cnt[0]];
    assign th_wire[26] = thresh_rom_26[step_cnt[0]];
    assign th_wire[27] = thresh_rom_27[step_cnt[0]];
    assign th_wire[28] = thresh_rom_28[step_cnt[0]];
    assign th_wire[29] = thresh_rom_29[step_cnt[0]];
    assign th_wire[30] = thresh_rom_30[step_cnt[0]];
    assign th_wire[31] = thresh_rom_31[step_cnt[0]];

    assign adp_sign_wire[0]  = adp_sign_rom_0[step_cnt[0]][0];
    assign adp_sign_wire[1]  = adp_sign_rom_1[step_cnt[0]][0];
    assign adp_sign_wire[2]  = adp_sign_rom_2[step_cnt[0]][0];
    assign adp_sign_wire[3]  = adp_sign_rom_3[step_cnt[0]][0];
    assign adp_sign_wire[4]  = adp_sign_rom_4[step_cnt[0]][0];
    assign adp_sign_wire[5]  = adp_sign_rom_5[step_cnt[0]][0];
    assign adp_sign_wire[6]  = adp_sign_rom_6[step_cnt[0]][0];
    assign adp_sign_wire[7]  = adp_sign_rom_7[step_cnt[0]][0];
    assign adp_sign_wire[8]  = adp_sign_rom_8[step_cnt[0]][0];
    assign adp_sign_wire[9]  = adp_sign_rom_9[step_cnt[0]][0];
    assign adp_sign_wire[10] = adp_sign_rom_10[step_cnt[0]][0];
    assign adp_sign_wire[11] = adp_sign_rom_11[step_cnt[0]][0];
    assign adp_sign_wire[12] = adp_sign_rom_12[step_cnt[0]][0];
    assign adp_sign_wire[13] = adp_sign_rom_13[step_cnt[0]][0];
    assign adp_sign_wire[14] = adp_sign_rom_14[step_cnt[0]][0];
    assign adp_sign_wire[15] = adp_sign_rom_15[step_cnt[0]][0];
    assign adp_sign_wire[16] = adp_sign_rom_16[step_cnt[0]][0];
    assign adp_sign_wire[17] = adp_sign_rom_17[step_cnt[0]][0];
    assign adp_sign_wire[18] = adp_sign_rom_18[step_cnt[0]][0];
    assign adp_sign_wire[19] = adp_sign_rom_19[step_cnt[0]][0];
    assign adp_sign_wire[20] = adp_sign_rom_20[step_cnt[0]][0];
    assign adp_sign_wire[21] = adp_sign_rom_21[step_cnt[0]][0];
    assign adp_sign_wire[22] = adp_sign_rom_22[step_cnt[0]][0];
    assign adp_sign_wire[23] = adp_sign_rom_23[step_cnt[0]][0];
    assign adp_sign_wire[24] = adp_sign_rom_24[step_cnt[0]][0];
    assign adp_sign_wire[25] = adp_sign_rom_25[step_cnt[0]][0];
    assign adp_sign_wire[26] = adp_sign_rom_26[step_cnt[0]][0];
    assign adp_sign_wire[27] = adp_sign_rom_27[step_cnt[0]][0];
    assign adp_sign_wire[28] = adp_sign_rom_28[step_cnt[0]][0];
    assign adp_sign_wire[29] = adp_sign_rom_29[step_cnt[0]][0];
    assign adp_sign_wire[30] = adp_sign_rom_30[step_cnt[0]][0];
    assign adp_sign_wire[31] = adp_sign_rom_31[step_cnt[0]][0];

    integer p;

    // =========================================================
    // Main pipeline
    // =========================================================
    always @(posedge aclk) begin
        if (!aresetn) begin
            m_axis_tvalid <= 1'b0;
            m_axis_tdata  <= 32'd0;
            s1_valid      <= 1'b0;
            s2_valid      <= 1'b0;
            step_cnt      <= 3'd0;

            for (p = 0; p < PE; p = p + 1) begin
                s1_mvau_pop[p]     <= 32'sd0;
                s1_adp_contrib[p]  <= 32'sd0;
                s1_threshold[p]    <= 32'sd0;
                s1_adp_sign[p]     <= 1'b0;
                s2_total_pop_q8[p] <= 32'sd0;
                s2_threshold[p]    <= 32'sd0;
            end
        end
        else if (!stall) begin
            // Stage 3: compare/output (unified Q8 >=)
            if (s2_valid) begin
                m_axis_tvalid <= 1'b1;
                for (p = 0; p < PE; p = p + 1) begin
                    m_axis_tdata[p] <= (s2_total_pop_q8[p] >= s2_threshold[p]) ? 1'b1 : 1'b0;
                end
            end
            else begin
                m_axis_tvalid <= 1'b0;
            end

            // Stage 2: widen MVAU popcount to Q8 and add/sub adapter contribution
            if (s1_valid) begin
                s2_valid <= 1'b1;
                for (p = 0; p < PE; p = p + 1) begin
                    s2_total_pop_q8[p] <= (s1_mvau_pop[p] <<< 8)
                                          + (s1_adp_sign[p] ? -s1_adp_contrib[p]
                                                            :  s1_adp_contrib[p]);
                    s2_threshold[p]    <= s1_threshold[p];
                end
            end
            else begin
                s2_valid <= 1'b0;
            end

            // Stage 1: capture
            if (in_fire) begin
                s1_valid <= 1'b1;
                for (p = 0; p < PE; p = p + 1) begin
                    s1_mvau_pop[p]    <= $signed(s_axis_1_tdata[(p*32) +: 32]);
                    s1_adp_contrib[p] <= adp_contrib_lut[s_axis_2_tdata[(p*8) +: 8]];
                    s1_threshold[p]   <= th_wire[p];
                    s1_adp_sign[p]    <= adp_sign_wire[p];
                end

                if (step_cnt == 3'd1)
                    step_cnt <= 3'd0;
                else
                    step_cnt <= step_cnt + 3'd1;
            end
            else begin
                s1_valid <= 1'b0;
            end
        end
    end

endmodule
