// ===========================================================================
// [交接導向註解]
// MVAU0 Matrix-Vector-Activate（MAC 核心）— Conv0 — threshold ROM 變 cfg 可寫
// 
// 改動明細（patch_finn_ips.py，vs *.pre_cfg_patch.bak）：
//  1. module 埠新增：input cfg_wen; input [5:0] cfg_waddr; input [31:0] cfg_wdata;（64-deep）
//  2. threshs_U 實例新增接線：.cfg_wen(cfg_wen) .cfg_waddr(cfg_waddr) .cfg_wdata(cfg_wdata)
//  → 把 cfg 寫入串接到可寫 threshold ROM（搭配同層 *_threshs_ROM_AUTO_1R.v）
// 
// 流程：FINN 生成 → 本論文修改此檔 → RTL/super_wrapper 整合 → SoC → FPGA。
// ===========================================================================

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingDataflowPartition_1_MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY,
        cfg_wen,
        cfg_waddr,
        cfg_wdata
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [23:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [7:0] weights_V_TDATA;
output   weights_V_TREADY;
input   cfg_wen;
input  [5:0] cfg_waddr;
input  [31:0] cfg_wdata;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln249_fu_228_p2;
wire   [0:0] icmp_ln253_fu_240_p2;
reg    ap_predicate_op49_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_659;
reg   [0:0] icmp_ln249_reg_659_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_712;
reg   [0:0] icmp_ln290_reg_712_pp0_iter1_reg;
reg    ap_predicate_op118_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] threshs_address0;
reg    threshs_ce0;
wire   [10:0] threshs_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_654;
wire   [0:0] icmp_ln249_reg_659_pp0_iter0_reg;
wire   [3:0] trunc_ln257_fu_302_p1;
reg   [7:0] weights_V_read_reg_671;
wire   [0:0] icmp_ln272_fu_351_p2;
reg   [0:0] icmp_ln272_reg_677;
wire   [0:0] local_temp_V_fu_357_p1;
reg   [0:0] local_temp_V_reg_682;
wire   [7:0] r_V_fu_361_p1;
reg   [7:0] r_V_reg_687;
wire  signed [8:0] sext_ln186_fu_375_p1;
reg  signed [8:0] sext_ln186_reg_692;
wire   [8:0] ret_V_1_fu_379_p2;
reg   [8:0] ret_V_1_reg_697;
wire  signed [8:0] sext_ln186_1_fu_395_p1;
reg  signed [8:0] sext_ln186_1_reg_702;
wire   [8:0] ret_V_2_fu_399_p2;
reg   [8:0] ret_V_2_reg_707;
wire   [0:0] icmp_ln290_fu_411_p2;
wire   [31:0] add_ln840_2_fu_537_p2;
reg   [31:0] add_ln840_2_reg_716;
reg   [23:0] ap_phi_mux_inElem_1_phi_fu_173_p20;
wire   [23:0] ap_phi_reg_pp0_iter0_inElem_1_reg_170;
wire   [23:0] tmp_fu_277_p11;
wire   [63:0] idxprom2_i_fu_543_p1;
reg   [31:0] sf_fu_86;
wire   [31:0] sf_2_fu_405_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [18:0] i_fu_90;
wire   [18:0] i_2_fu_234_p2;
reg   [18:0] ap_sig_allocacmp_i_1;
reg   [31:0] add_i9_i_232_fu_94;
reg   [23:0] inputBuf_V_fu_98;
reg   [23:0] inputBuf_V_1_fu_102;
reg   [23:0] inputBuf_V_2_fu_106;
reg   [23:0] inputBuf_V_3_fu_110;
reg   [23:0] inputBuf_V_4_fu_114;
reg   [23:0] inputBuf_V_5_fu_118;
reg   [23:0] inputBuf_V_6_fu_122;
reg   [23:0] inputBuf_V_7_fu_126;
reg   [23:0] inputBuf_V_8_fu_130;
reg   [31:0] nf_1_fu_134;
wire   [31:0] nf_3_fu_434_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [3:0] tmp_fu_277_p10;
wire   [7:0] r_V_1_fu_365_p4;
wire   [7:0] r_V_2_fu_385_p4;
wire   [31:0] nf_fu_422_p2;
wire   [0:0] icmp_ln302_fu_428_p2;
wire  signed [8:0] sext_ln90_fu_481_p1;
wire   [8:0] ret_V_fu_484_p2;
wire   [8:0] select_ln90_fu_490_p3;
wire   [0:0] local_temp_V_1_fu_467_p3;
wire   [8:0] select_ln90_1_fu_501_p3;
wire   [0:0] local_temp_V_2_fu_474_p3;
wire   [8:0] select_ln90_2_fu_511_p3;
wire   [31:0] select_ln272_fu_460_p3;
wire  signed [31:0] sext_ln840_fu_497_p1;
wire  signed [9:0] sext_ln628_fu_507_p1;
wire  signed [9:0] sext_ln840_1_fu_517_p1;
wire   [9:0] add_ln840_1_fu_527_p2;
wire  signed [31:0] sext_ln840_2_fu_533_p1;
wire   [31:0] add_ln840_fu_521_p2;
wire  signed [31:0] sext_ln1039_fu_552_p1;
wire   [0:0] icmp_ln1039_fu_556_p2;
wire   [0:0] result_V_fu_561_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
reg    ap_condition_545;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

StreamingDataflowPartition_1_MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
threshs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_address0),
    .ce0(threshs_ce0),
    .q0(threshs_q0),
    .cfg_wen(cfg_wen),
    .cfg_waddr(cfg_waddr),
    .cfg_wdata(cfg_wdata)
);

StreamingDataflowPartition_1_MVAU_hls_0_mux_94_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 24 ),
    .din5_WIDTH( 24 ),
    .din6_WIDTH( 24 ),
    .din7_WIDTH( 24 ),
    .din8_WIDTH( 24 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 24 ))
mux_94_24_1_1_U1(
    .din0(inputBuf_V_fu_98),
    .din1(inputBuf_V_1_fu_102),
    .din2(inputBuf_V_2_fu_106),
    .din3(inputBuf_V_3_fu_110),
    .din4(inputBuf_V_4_fu_114),
    .din5(inputBuf_V_5_fu_118),
    .din6(inputBuf_V_6_fu_122),
    .din7(inputBuf_V_7_fu_126),
    .din8(inputBuf_V_8_fu_130),
    .din9(tmp_fu_277_p10),
    .dout(tmp_fu_277_p11)
);

StreamingDataflowPartition_1_MVAU_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_545)) begin
        if ((icmp_ln249_fu_228_p2 == 1'd0)) begin
            i_fu_90 <= i_2_fu_234_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_90 <= 19'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_545)) begin
        if (((icmp_ln249_fu_228_p2 == 1'd0) & (icmp_ln290_fu_411_p2 == 1'd1))) begin
            nf_1_fu_134 <= nf_3_fu_434_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_134 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_545)) begin
        if (((icmp_ln249_fu_228_p2 == 1'd0) & (icmp_ln290_fu_411_p2 == 1'd1))) begin
            sf_fu_86 <= 32'd0;
        end else if (((icmp_ln249_fu_228_p2 == 1'd0) & (icmp_ln290_fu_411_p2 == 1'd0))) begin
            sf_fu_86 <= sf_2_fu_405_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_86 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_659_pp0_iter0_reg == 1'd0))) begin
        add_i9_i_232_fu_94 <= add_ln840_2_fu_537_p2;
        add_ln840_2_reg_716 <= add_ln840_2_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_659 <= icmp_ln249_fu_228_p2;
        nf_2_reg_654 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln249_reg_659_pp0_iter1_reg <= icmp_ln249_reg_659;
        icmp_ln290_reg_712_pp0_iter1_reg <= icmp_ln290_reg_712;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln272_reg_677 <= icmp_ln272_fu_351_p2;
        icmp_ln290_reg_712 <= icmp_ln290_fu_411_p2;
        local_temp_V_reg_682 <= local_temp_V_fu_357_p1;
        r_V_reg_687 <= r_V_fu_361_p1;
        ret_V_1_reg_697 <= ret_V_1_fu_379_p2;
        ret_V_2_reg_707 <= ret_V_2_fu_399_p2;
        sext_ln186_1_reg_702 <= sext_ln186_1_fu_395_p1;
        sext_ln186_reg_692 <= sext_ln186_fu_375_p1;
        weights_V_read_reg_671 <= weights_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd1))) begin
        inputBuf_V_1_fu_102 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd2))) begin
        inputBuf_V_2_fu_106 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd3))) begin
        inputBuf_V_3_fu_110 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd4))) begin
        inputBuf_V_4_fu_114 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd5))) begin
        inputBuf_V_5_fu_118 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd6))) begin
        inputBuf_V_6_fu_122 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd7))) begin
        inputBuf_V_7_fu_126 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & ~(trunc_ln257_fu_302_p1 == 4'd7) & ~(trunc_ln257_fu_302_p1 == 4'd0) & ~(trunc_ln257_fu_302_p1 == 4'd1) & ~(trunc_ln257_fu_302_p1 == 4'd2) & ~(trunc_ln257_fu_302_p1 == 4'd3) & ~(trunc_ln257_fu_302_p1 == 4'd4) & ~(trunc_ln257_fu_302_p1 == 4'd5) & ~(trunc_ln257_fu_302_p1 == 4'd6) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        inputBuf_V_8_fu_130 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_302_p1 == 4'd0))) begin
        inputBuf_V_fu_98 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_228_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_240_p2 == 1'd0) & (icmp_ln249_fu_228_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_173_p20 = tmp_fu_277_p11;
    end else if ((((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd7)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd0)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd1)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd2)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd3)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd4)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd5)) | ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0) & (trunc_ln257_fu_302_p1 == 4'd6)) | (~(trunc_ln257_fu_302_p1 == 4'd7) & ~(trunc_ln257_fu_302_p1 == 4'd0) & ~(trunc_ln257_fu_302_p1 == 4'd1) & ~(trunc_ln257_fu_302_p1 == 4'd2) & ~(trunc_ln257_fu_302_p1 == 4'd3) & ~(trunc_ln257_fu_302_p1 == 4'd4) & ~(trunc_ln257_fu_302_p1 == 4'd5) & ~(trunc_ln257_fu_302_p1 == 4'd6) & (icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0)))) begin
        ap_phi_mux_inElem_1_phi_fu_173_p20 = in0_V_TDATA;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_173_p20 = ap_phi_reg_pp0_iter0_inElem_1_reg_170;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 19'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_90;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_134;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_86;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op49_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op49_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op118_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op118_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        threshs_ce0 = 1'b1;
    end else begin
        threshs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_228_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_659_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln840_1_fu_527_p2 = ($signed(sext_ln628_fu_507_p1) + $signed(sext_ln840_1_fu_517_p1));

assign add_ln840_2_fu_537_p2 = ($signed(sext_ln840_2_fu_533_p1) + $signed(add_ln840_fu_521_p2));

assign add_ln840_fu_521_p2 = ($signed(select_ln272_fu_460_p3) + $signed(sext_ln840_fu_497_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_545 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op118_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_228_p2 == 1'd0)) | ((ap_predicate_op49_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_170 = 'bx;

always @ (*) begin
    ap_predicate_op118_write_state3 = ((icmp_ln290_reg_712_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_659_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op49_read_state1 = ((icmp_ln253_fu_240_p2 == 1'd1) & (icmp_ln249_fu_228_p2 == 1'd0));
end

assign i_2_fu_234_p2 = (ap_sig_allocacmp_i_1 + 19'd1);

assign icmp_ln1039_fu_556_p2 = (($signed(add_ln840_2_reg_716) < $signed(sext_ln1039_fu_552_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_228_p2 = ((ap_sig_allocacmp_i_1 == 19'd518400) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_659_pp0_iter0_reg = icmp_ln249_reg_659;

assign icmp_ln253_fu_240_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_351_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_411_p2 = ((sf_2_fu_405_p2 == 32'd9) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_428_p2 = ((nf_fu_422_p2 == 32'd64) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_543_p1 = nf_2_reg_654;

assign local_temp_V_1_fu_467_p3 = weights_V_read_reg_671[32'd1];

assign local_temp_V_2_fu_474_p3 = weights_V_read_reg_671[32'd2];

assign local_temp_V_fu_357_p1 = weights_V_TDATA[0:0];

assign nf_3_fu_434_p3 = ((icmp_ln302_fu_428_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_422_p2);

assign nf_fu_422_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = result_V_fu_561_p2;

assign r_V_1_fu_365_p4 = {{ap_phi_mux_inElem_1_phi_fu_173_p20[15:8]}};

assign r_V_2_fu_385_p4 = {{ap_phi_mux_inElem_1_phi_fu_173_p20[23:16]}};

assign r_V_fu_361_p1 = ap_phi_mux_inElem_1_phi_fu_173_p20[7:0];

assign result_V_fu_561_p2 = (icmp_ln1039_fu_556_p2 ^ 1'd1);

assign ret_V_1_fu_379_p2 = ($signed(9'd0) - $signed(sext_ln186_fu_375_p1));

assign ret_V_2_fu_399_p2 = ($signed(9'd0) - $signed(sext_ln186_1_fu_395_p1));

assign ret_V_fu_484_p2 = ($signed(9'd0) - $signed(sext_ln90_fu_481_p1));

assign select_ln272_fu_460_p3 = ((icmp_ln272_reg_677[0:0] == 1'b1) ? 32'd0 : add_i9_i_232_fu_94);

assign select_ln90_1_fu_501_p3 = ((local_temp_V_1_fu_467_p3[0:0] == 1'b1) ? sext_ln186_reg_692 : ret_V_1_reg_697);

assign select_ln90_2_fu_511_p3 = ((local_temp_V_2_fu_474_p3[0:0] == 1'b1) ? sext_ln186_1_reg_702 : ret_V_2_reg_707);

assign select_ln90_fu_490_p3 = ((local_temp_V_reg_682[0:0] == 1'b1) ? sext_ln90_fu_481_p1 : ret_V_fu_484_p2);

assign sext_ln1039_fu_552_p1 = $signed(threshs_q0);

assign sext_ln186_1_fu_395_p1 = $signed(r_V_2_fu_385_p4);

assign sext_ln186_fu_375_p1 = $signed(r_V_1_fu_365_p4);

assign sext_ln628_fu_507_p1 = $signed(select_ln90_1_fu_501_p3);

assign sext_ln840_1_fu_517_p1 = $signed(select_ln90_2_fu_511_p3);

assign sext_ln840_2_fu_533_p1 = $signed(add_ln840_1_fu_527_p2);

assign sext_ln840_fu_497_p1 = $signed(select_ln90_fu_490_p3);

assign sext_ln90_fu_481_p1 = $signed(r_V_reg_687);

assign sf_2_fu_405_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign threshs_address0 = idxprom2_i_fu_543_p1;

assign tmp_fu_277_p10 = ap_sig_allocacmp_sf_1[3:0];

assign trunc_ln257_fu_302_p1 = ap_sig_allocacmp_sf_1[3:0];

endmodule //StreamingDataflowPartition_1_MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch
