#!/usr/bin/env python3
"""
Generate multi-branch (M=2/3/4) Super_Wrapper + Stream_Adder_Threshold RTL for
all 5 adapter sites, in both build styles:
  compact : PE=1 everywhere  (mvau_pipeline_runtime_3ds_pe1 style)
  tp      : throughput PE={32,16,16,4,1} (mvau_pipeline_runtime style)

Architecture = thesis Eq.(multi_adapter): M parallel adapter branches, each an
unchanged Adapter_MVAU{n} instance with its own weights, whose Q8 contributions
(via per-branch contrib LUTs) are summed before the shared threshold compare.
cfg map per site is unchanged except new word 1 = branch_sel (routes rc/down/up
and contrib-LUT cfg writes to the selected branch; thresh/sign stay shared).

Module/port names identical to the M=1 sources, so the packaged IPs drop into
the existing FINN block design without BD edits.
"""
import os

ROOT = "/home/barkie1/mvau_multibranch_synth"

SITE = {
    1: dict(IN_CH=64,  OUT_CH=64,  HIDDEN=16, UPW=32, K=576,  pol=False),
    2: dict(IN_CH=64,  OUT_CH=128, HIDDEN=16, UPW=32, K=576,  pol=False),
    3: dict(IN_CH=128, OUT_CH=128, HIDDEN=32, UPW=32, K=1152, pol=False),
    4: dict(IN_CH=128, OUT_CH=256, HIDDEN=32, UPW=32, K=1152, pol=False),
    5: dict(IN_CH=256, OUT_CH=256, HIDDEN=64, UPW=64, K=2304, pol=True),
}
PE_TP = {1: 32, 2: 16, 3: 16, 4: 4, 5: 1}
OUTW_TP = {1: 32, 2: 16, 3: 16, 4: 8, 5: 8}


def clog2(x):
    return max(1, (x - 1).bit_length())


# ---------------------------------------------------------------------------
def gen_wrapper(style, n, M):
    pe = 1 if style == "compact" else PE_TP[n]
    ww = 32 * pe                      # weights stream width
    mw = 32 * pe                      # mvau out width
    aw = 8 * pe                       # adapter/fifo width
    ow = 8 if style == "compact" else OUTW_TP[n]
    pol_scalar = (pe == 1)            # scalar adder emits 1 bit, wrapper pads

    B = range(M)
    l = []
    a = l.append
    a("`timescale 1ns / 1ps")
    a("")
    a(f"// MVAU{n}_Super_Wrapper — multi-branch M={M} ({style}), generated by")
    a("// gen_multibranch_rtl.py. Ports identical to the M=1 wrapper.")
    a(f"module MVAU{n}_Super_Wrapper (")
    a("    input  wire        ap_clk,")
    a("    input  wire        ap_rst_n,")
    a("")
    a("    input  wire [31:0] in0_V_TDATA,")
    a("    input  wire        in0_V_TVALID,")
    a("    output wire        in0_V_TREADY,")
    a("")
    a(f"    input  wire [{ww-1}:0] weights_V_TDATA,")
    a("    input  wire        weights_V_TVALID,")
    a("    output wire        weights_V_TREADY,")
    a("")
    a(f"    output wire [{ow-1}:0]  out_V_TDATA,")
    a("    output wire        out_V_TVALID,")
    a("    input  wire        out_V_TREADY,")
    a("")
    a("    // Runtime config write port (from adapter_cfg_hub)")
    a("    input  wire [10:0] cfg_waddr,")
    a("    input  wire [31:0] cfg_wdata,")
    a("    input  wire        cfg_wen")
    a(");")
    a("")
    a("    // word 0: adapter_enable, word 1: branch_sel (new for multi-branch)")
    a("    reg        adapter_enable;")
    a("    reg [1:0]  branch_sel;")
    a("    always @(posedge ap_clk) begin")
    a("        if (!ap_rst_n) begin")
    a("            adapter_enable <= 1'b1;")
    a("            branch_sel     <= 2'd0;")
    a("        end else if (cfg_wen) begin")
    a("            if (cfg_waddr == 11'd0) adapter_enable <= cfg_wdata[0];")
    a("            if (cfg_waddr == 11'd1) branch_sel     <= cfg_wdata[1:0];")
    a("        end")
    a("    end")
    a("")
    a("    // ---- broadcast in0 to MVAU + all branches (all-ready fork, same")
    a("    //      semantics as the M=1 Stream_Splitter) ----")
    a("    wire mvau_in_ready;")
    for b in B:
        a(f"    wire br_in_ready_b{b};")
    rdys = " && ".join(["mvau_in_ready"] + [f"br_in_ready_b{b}" for b in B])
    a(f"    assign in0_V_TREADY = {rdys};")
    a("    wire bcast_valid = in0_V_TVALID && in0_V_TREADY;")
    a("")
    a(f"    wire [{mw-1}:0] mvau_to_add_tdata;")
    a("    wire mvau_to_add_tvalid, mvau_to_add_tready;")
    a("")
    a(f"    StreamingDataflowPartition_1_StreamingDataflowPartition_1_MVAU_hls_{n}_0 mvau_inst (")
    a("        .ap_clk(ap_clk), .ap_rst_n(ap_rst_n),")
    a("        .in0_V_TVALID(bcast_valid), .in0_V_TREADY(mvau_in_ready), .in0_V_TDATA(in0_V_TDATA),")
    a("        .weights_V_TVALID(weights_V_TVALID), .weights_V_TREADY(weights_V_TREADY), .weights_V_TDATA(weights_V_TDATA),")
    a("        .out_V_TVALID(mvau_to_add_tvalid), .out_V_TREADY(mvau_to_add_tready), .out_V_TDATA(mvau_to_add_tdata)")
    a("    );")
    for b in B:
        a("")
        a(f"    // ------------------ branch {b} ------------------")
        a(f"    wire [{aw-1}:0] adapt_to_fifo_tdata_b{b}, fifo_to_add_tdata_b{b};")
        a(f"    wire adapt_to_fifo_tvalid_b{b}, adapt_to_fifo_tready_b{b};")
        a(f"    wire fifo_to_add_tvalid_b{b}, fifo_to_add_tready_b{b};")
        a(f"    wire cfg_wen_b{b} = cfg_wen && (branch_sel == 2'd{b});")
        a("")
        adap_mod = "Adapter_Generic" if (style == "tp" and n == 5) else f"Adapter_MVAU{n}"
        a(f"    {adap_mod} adapter_inst_b{b} (")
        a("        .aclk(ap_clk), .aresetn(ap_rst_n),")
        a(f"        .s_axis_tdata(in0_V_TDATA), .s_axis_tvalid(bcast_valid), .s_axis_tready(br_in_ready_b{b}),")
        a(f"        .m_axis_tdata(adapt_to_fifo_tdata_b{b}), .m_axis_tvalid(adapt_to_fifo_tvalid_b{b}), .m_axis_tready(adapt_to_fifo_tready_b{b}),")
        a(f"        .cfg_waddr(cfg_waddr), .cfg_wdata(cfg_wdata), .cfg_wen(cfg_wen_b{b})")
        a("    );")
        a("")
        a(f"    Simple_FIFO_mvau{n} #(.WIDTH({aw}), .DEPTH_LOG2(4)) fifo_inst_b{b} (")
        a("        .clk(ap_clk), .rst_n(ap_rst_n),")
        a(f"        .s_axis_tdata(adapt_to_fifo_tdata_b{b}), .s_axis_tvalid(adapt_to_fifo_tvalid_b{b}), .s_axis_tready(adapt_to_fifo_tready_b{b}),")
        a(f"        .m_axis_tdata(fifo_to_add_tdata_b{b}), .m_axis_tvalid(fifo_to_add_tvalid_b{b}), .m_axis_tready(fifo_to_add_tready_b{b})")
        a("    );")
    a("")
    if pol_scalar and style == "compact" or pe == 1:
        a("    wire adder_out_bit;")
        a(f"    assign out_V_TDATA = {{{ow-1}'b0, adder_out_bit}};")
        out_conn = ".m_axis_tdata(adder_out_bit)"
    else:
        out_conn = ".m_axis_tdata(out_V_TDATA)"
    a(f"    Stream_Adder_Threshold_mvau{n} adder_thresh_inst (")
    a("        .aclk(ap_clk), .aresetn(ap_rst_n),")
    a("        .s_axis_1_tdata(mvau_to_add_tdata), .s_axis_1_tvalid(mvau_to_add_tvalid), .s_axis_1_tready(mvau_to_add_tready),")
    for b in B:
        a(f"        .s_axis_2_b{b}_tdata(fifo_to_add_tdata_b{b}), .s_axis_2_b{b}_tvalid(fifo_to_add_tvalid_b{b}), .s_axis_2_b{b}_tready(fifo_to_add_tready_b{b}),")
    a(f"        {out_conn}, .m_axis_tvalid(out_V_TVALID), .m_axis_tready(out_V_TREADY),")
    a("        .cfg_waddr(cfg_waddr), .cfg_wdata(cfg_wdata), .cfg_wen(cfg_wen), .branch_sel(branch_sel),")
    a("        .adapter_enable(adapter_enable)")
    a("    );")
    a("")
    a("endmodule")
    return "\n".join(l) + "\n"


# ---------------------------------------------------------------------------
def gen_adder_scalar(style, n, M, alphas=None):
    """PE=1 adder (all compact sites + tp site 5). Site 5 uses pol XOR form.
    alphas: list of per-branch alpha_q8 ints -> bake contrib as constant
    multiply (deployed throughput style) instead of cfg-writable LUTs."""
    cfg = SITE[n]
    OUT_CH, K, pol = cfg["OUT_CH"], cfg["K"], cfg["pol"]
    OFFSET = cfg["UPW"] - cfg["HIDDEN"] // 2
    B = range(M)
    l = []
    a = l.append
    a("`timescale 1ns / 1ps")
    a("")
    a(f"// Stream_Adder_Threshold_mvau{n} — multi-branch M={M}, PE=1 ({style}).")
    a(f"// total_q8 = {'((pol ? K-pop : pop) << 8) + sum_b contrib_b ; out = (>=thr) ^ pol' if pol else '(pop << 8) + (sign ? -sum_b contrib_b : +sum_b contrib_b) ; out = (>= thr)'}")
    if alphas is not None:
        a("(* use_dsp = \"no\" *)")
    a(f"module Stream_Adder_Threshold_mvau{n} (")
    a("    input  wire                  aclk,")
    a("    input  wire                  aresetn,")
    a("")
    a("    input  wire [31:0]           s_axis_1_tdata,")
    a("    input  wire                  s_axis_1_tvalid,")
    a("    output wire                  s_axis_1_tready,")
    a("")
    for b in B:
        a(f"    input  wire [7:0]            s_axis_2_b{b}_tdata,")
        a(f"    input  wire                  s_axis_2_b{b}_tvalid,")
        a(f"    output wire                  s_axis_2_b{b}_tready,")
        a("")
    a("    output reg                   m_axis_tdata,")
    a("    output reg                   m_axis_tvalid,")
    a("    input  wire                  m_axis_tready,")
    a("")
    a("    input  wire [10:0]           cfg_waddr,")
    a("    input  wire [31:0]           cfg_wdata,")
    a("    input  wire                  cfg_wen,")
    a("    input  wire [1:0]            branch_sel,")
    a("    input  wire                  adapter_enable")
    a(");")
    a(f"    parameter OUT_CH = {OUT_CH};")
    if pol:
        a(f"    parameter K_TOTAL = {K};")
    a("")
    a("    (* ram_style = \"distributed\" *) reg signed [31:0] thresh_rom   [0:OUT_CH-1];")
    a("    (* ram_style = \"distributed\" *) reg               adp_sign_rom [0:OUT_CH-1];")
    if alphas is None:
        for b in B:
            a(f"    (* ram_style = \"distributed\" *) reg signed [31:0] adp_contrib_lut_b{b} [0:255];")
    else:
        a(f"    localparam signed [31:0] CONTRIB_OFFSET = {OFFSET};")
        for b in B:
            a(f"    localparam signed [31:0] ALPHA_Q8_B{b} = {alphas[b]};  // baked from checkpoint")
    a("")
    a("    localparam CFG_THRESH_BASE = 11'd1152;")
    a("    localparam CFG_SIGN_BASE   = 11'd1408;")
    a("    localparam CFG_LUT_BASE    = 11'd1664;")
    a("")
    a("    always @(posedge aclk) begin")
    a("        if (cfg_wen) begin")
    a("            if (cfg_waddr >= CFG_THRESH_BASE && cfg_waddr < CFG_THRESH_BASE + OUT_CH)")
    a("                thresh_rom[cfg_waddr - CFG_THRESH_BASE] <= $signed(cfg_wdata);")
    a("            if (cfg_waddr >= CFG_SIGN_BASE && cfg_waddr < CFG_SIGN_BASE + OUT_CH)")
    a("                adp_sign_rom[cfg_waddr - CFG_SIGN_BASE] <= cfg_wdata[0];")
    if alphas is None:
        for b in B:
            a(f"            if (cfg_waddr >= CFG_LUT_BASE && cfg_waddr < CFG_LUT_BASE + 256 && branch_sel == 2'd{b})")
            a(f"                adp_contrib_lut_b{b}[cfg_waddr - CFG_LUT_BASE] <= $signed(cfg_wdata);")
    a("        end")
    a("    end")
    a("")
    a("    reg [$clog2(OUT_CH)-1:0] ch_cnt;")
    a("    wire stall = m_axis_tvalid && !m_axis_tready;")
    all_v = " && ".join(f"s_axis_2_b{b}_tvalid" for b in B)
    a(f"    wire all_br_valid = {all_v};")
    a("    wire in_fire = s_axis_1_tvalid && all_br_valid && !stall;")
    a("    assign s_axis_1_tready = !stall && all_br_valid;")
    for b in B:
        others = " && ".join(["s_axis_1_tvalid"] + [f"s_axis_2_b{x}_tvalid" for x in B if x != b])
        a(f"    assign s_axis_2_b{b}_tready = !stall && {others};")
    a("")
    a("    reg                    s1_valid;")
    a("    reg signed [31:0]      s1_mvau_pop;")
    for b in B:
        a(f"    (* use_dsp = \"no\" *) reg signed [31:0]      s1_adp_contrib_b{b};")
    a("    reg signed [31:0]      s1_threshold;")
    a("    reg                    s1_adp_sign;")
    a("")
    a("    reg                    s2_valid;")
    a("    reg signed [31:0]      s2_total_q8;")
    a("    reg signed [31:0]      s2_threshold;")
    if pol:
        a("    reg                    s2_pol;")
    a("")
    csum = " + ".join(f"s1_adp_contrib_b{b}" for b in B)
    a(f"    wire signed [31:0] contrib_sum_s1 = {csum};")
    a("")
    a("    always @(posedge aclk) begin")
    a("        if (!aresetn) begin")
    a("            ch_cnt <= 0;")
    a("            m_axis_tvalid <= 0; m_axis_tdata <= 0;")
    a("            s1_valid <= 0; s2_valid <= 0;")
    a("        end else if (!stall) begin")
    a("            // Stage 3 (compare/output)")
    a("            if (s2_valid) begin")
    a("                m_axis_tvalid <= 1'b1;")
    if pol:
        a("                m_axis_tdata  <= ((s2_total_q8 >= s2_threshold) ? 1'b1 : 1'b0) ^ s2_pol;")
    else:
        a("                m_axis_tdata  <= (s2_total_q8 >= s2_threshold) ? 1'b1 : 1'b0;")
    a("            end else begin")
    a("                m_axis_tvalid <= 1'b0;")
    a("            end")
    a("")
    a("            // Stage 2 (widen + add summed branch contributions)")
    a("            if (s1_valid) begin")
    a("                s2_valid <= 1'b1;")
    if pol:
        a("                if (adapter_enable) begin")
        a("                    if (s1_adp_sign)")
        a("                        s2_total_q8 <= (($signed(K_TOTAL) - s1_mvau_pop) <<< 8) + contrib_sum_s1;")
        a("                    else")
        a("                        s2_total_q8 <= (s1_mvau_pop <<< 8) + contrib_sum_s1;")
        a("                end else begin")
        a("                    if (s1_adp_sign)")
        a("                        s2_total_q8 <= ($signed(K_TOTAL) - s1_mvau_pop) <<< 8;")
        a("                    else")
        a("                        s2_total_q8 <= s1_mvau_pop <<< 8;")
        a("                end")
        a("                s2_pol       <= s1_adp_sign;")
    else:
        a("                if (adapter_enable)")
        a("                    s2_total_q8 <= (s1_mvau_pop <<< 8) +")
        a("                                   (s1_adp_sign ? -contrib_sum_s1 : contrib_sum_s1);")
        a("                else")
        a("                    s2_total_q8 <= (s1_mvau_pop <<< 8);")
    a("                s2_threshold <= s1_threshold;")
    a("            end else begin")
    a("                s2_valid <= 1'b0;")
    a("            end")
    a("")
    a("            // Stage 1 (capture + per-branch LUT lookup)")
    a("            if (in_fire) begin")
    a("                s1_valid       <= 1'b1;")
    a("                s1_mvau_pop    <= $signed(s_axis_1_tdata);")
    for b in B:
        if alphas is None:
            a(f"                s1_adp_contrib_b{b} <= adp_contrib_lut_b{b}[s_axis_2_b{b}_tdata];")
        else:
            a(f"                s1_adp_contrib_b{b} <= ($signed({{24'd0, s_axis_2_b{b}_tdata}}) - CONTRIB_OFFSET) * ALPHA_Q8_B{b};")
    a("                s1_threshold   <= thresh_rom[ch_cnt];")
    a("                s1_adp_sign    <= adp_sign_rom[ch_cnt];")
    a("")
    a("                if (ch_cnt == OUT_CH - 1) ch_cnt <= 0;")
    a("                else                       ch_cnt <= ch_cnt + 1;")
    a("            end else begin")
    a("                s1_valid <= 1'b0;")
    a("            end")
    a("        end")
    a("    end")
    a("")
    a("endmodule")
    return "\n".join(l) + "\n"


# ---------------------------------------------------------------------------
def gen_adder_pe(n, M, alphas=None):
    """tp PE-wide adder, per-PE storage structure (deployed 'LUT fix' form).

    Every cfg-writable memory has exactly 1 write + 1 read port so it maps to
    distributed RAM: per-lane thresh/sign column arrays (lane p holds channels
    ch = s*PE+p) + per-lane copies of each branch's 256-entry contrib LUT
    (cfg write broadcast to all lane copies of the selected branch).
    """
    cfg = SITE[n]
    OUT_CH = cfg["OUT_CH"]
    PE = PE_TP[n]
    OUT_STEPS = OUT_CH // PE
    OW = OUTW_TP[n]
    SW = clog2(OUT_STEPS)
    PB = clog2(PE)
    OFFSET = cfg["UPW"] - cfg["HIDDEN"] // 2
    B = range(M)
    l = []
    a = l.append
    a("`timescale 1ns / 1ps")
    a("")
    a(f"// Stream_Adder_Threshold_mvau{n} — multi-branch M={M}, PE={PE} (throughput),")
    a("// per-PE storage structure (1W1R per array -> distributed RAM).")
    a("// Per lane p (ch = step*PE+p): total_q8 = (mvau_pop << 8) + (sign ? -sum : +sum),")
    a("// sum = sum over branches of lane-local contrib LUT lookups; out = (>= thr).")
    a("(* use_dsp = \"no\" *)")
    a(f"module Stream_Adder_Threshold_mvau{n} (")
    a("    input  wire                  aclk,")
    a("    input  wire                  aresetn,")
    a("")
    a(f"    input  wire [{PE*32-1}:0]         s_axis_1_tdata,")
    a("    input  wire                  s_axis_1_tvalid,")
    a("    output wire                  s_axis_1_tready,")
    a("")
    for b in B:
        a(f"    input  wire [{PE*8-1}:0]          s_axis_2_b{b}_tdata,")
        a(f"    input  wire                  s_axis_2_b{b}_tvalid,")
        a(f"    output wire                  s_axis_2_b{b}_tready,")
        a("")
    a(f"    output reg  [{OW-1}:0]           m_axis_tdata,")
    a("    output reg                   m_axis_tvalid,")
    a("    input  wire                  m_axis_tready,")
    a("")
    a("    input  wire [10:0]           cfg_waddr,")
    a("    input  wire [31:0]           cfg_wdata,")
    a("    input  wire                  cfg_wen,")
    a("    input  wire [1:0]            branch_sel,")
    a("    input  wire                  adapter_enable")
    a(");")
    a(f"    parameter PE        = {PE};")
    a(f"    parameter OUT_CH    = {OUT_CH};")
    a(f"    parameter OUT_STEPS = {OUT_STEPS};")
    a("")
    a("    localparam CFG_THRESH_BASE = 11'd1152;")
    a("    localparam CFG_SIGN_BASE   = 11'd1408;")
    a(f"    localparam signed [31:0] CONTRIB_OFFSET = {OFFSET};")
    for b in B:
        a(f"    localparam signed [31:0] ALPHA_Q8_B{b} = {alphas[b]};  // baked from checkpoint")
    a("")
    a(f"    reg [{SW-1}:0] step_cnt;")
    a("")
    a("    wire stall = m_axis_tvalid && !m_axis_tready;")
    all_v = " && ".join(f"s_axis_2_b{b}_tvalid" for b in B)
    a(f"    wire all_br_valid = {all_v};")
    a("    wire in_fire = s_axis_1_tvalid && all_br_valid && !stall;")
    a("    assign s_axis_1_tready = !stall && all_br_valid;")
    for b in B:
        others = " && ".join(["s_axis_1_tvalid"] + [f"s_axis_2_b{x}_tvalid" for x in B if x != b])
        a(f"    assign s_axis_2_b{b}_tready = !stall && {others};")
    a("")
    a("    reg s1_valid, s2_valid;")
    a(f"    wire [{PE-1}:0] cmp_bit;")
    a("")
    a("    // ---- per-lane storage + datapath ----")
    a("    genvar gp;")
    a("    generate")
    a("        for (gp = 0; gp < PE; gp = gp + 1) begin : g_lane")
    a("            // lane-column thresh/sign: entry s = channel s*PE+gp (1W1R)")
    a("            (* ram_style = \"distributed\" *) reg signed [31:0] th_mem [0:OUT_STEPS-1];")
    a("            (* ram_style = \"distributed\" *) reg               sg_mem [0:OUT_STEPS-1];")
    a("")
    a("            always @(posedge aclk) begin")
    a("                if (cfg_wen) begin")
    a("                    if (cfg_waddr >= CFG_THRESH_BASE && cfg_waddr < CFG_THRESH_BASE + OUT_CH")
    a(f"                        && ((cfg_waddr - CFG_THRESH_BASE) & (PE-1)) == gp)")
    a(f"                        th_mem[(cfg_waddr - CFG_THRESH_BASE) >> {PB}] <= $signed(cfg_wdata);")
    a("                    if (cfg_waddr >= CFG_SIGN_BASE && cfg_waddr < CFG_SIGN_BASE + OUT_CH")
    a(f"                        && ((cfg_waddr - CFG_SIGN_BASE) & (PE-1)) == gp)")
    a(f"                        sg_mem[(cfg_waddr - CFG_SIGN_BASE) >> {PB}] <= cfg_wdata[0];")
    a("                end")
    a("            end")
    a("")
    a("            reg signed [31:0] s1_mvau_pop;")
    for b in B:
        a(f"            reg signed [31:0] s1_contrib_b{b};")
    a("            reg signed [31:0] s1_threshold;")
    a("            reg               s1_adp_sign;")
    a("            reg signed [31:0] s2_total_q8;")
    a("            reg signed [31:0] s2_threshold;")
    csum = " + ".join(f"s1_contrib_b{b}" for b in B)
    a(f"            wire signed [31:0] contrib_sum = {csum};")
    a("")
    a("            always @(posedge aclk) begin")
    a("                if (!aresetn) begin")
    a("                    s1_mvau_pop <= 32'sd0; s1_threshold <= 32'sd0; s1_adp_sign <= 1'b0;")
    for b in B:
        a(f"                    s1_contrib_b{b} <= 32'sd0;")
    a("                    s2_total_q8 <= 32'sd0; s2_threshold <= 32'sd0;")
    a("                end else if (!stall) begin")
    a("                    if (s1_valid) begin")
    a("                        if (adapter_enable)")
    a("                            s2_total_q8 <= (s1_mvau_pop <<< 8)")
    a("                                           + (s1_adp_sign ? -contrib_sum : contrib_sum);")
    a("                        else")
    a("                            s2_total_q8 <= (s1_mvau_pop <<< 8);")
    a("                        s2_threshold <= s1_threshold;")
    a("                    end")
    a("                    if (in_fire) begin")
    a("                        s1_mvau_pop  <= $signed(s_axis_1_tdata[(gp*32) +: 32]);")
    for b in B:
        a(f"                        s1_contrib_b{b} <= ($signed({{24'd0, s_axis_2_b{b}_tdata[(gp*8) +: 8]}}) - CONTRIB_OFFSET) * ALPHA_Q8_B{b};")
    a("                        s1_threshold <= th_mem[step_cnt];")
    a("                        s1_adp_sign  <= sg_mem[step_cnt];")
    a("                    end")
    a("                end")
    a("            end")
    a("")
    a("            assign cmp_bit[gp] = (s2_total_q8 >= s2_threshold);")
    a("        end")
    a("    endgenerate")
    a("")
    a("    // ---- central control ----")
    a("    always @(posedge aclk) begin")
    a("        if (!aresetn) begin")
    a("            m_axis_tvalid <= 1'b0;")
    a(f"            m_axis_tdata  <= {OW}'d0;")
    a("            s1_valid      <= 1'b0;")
    a("            s2_valid      <= 1'b0;")
    a("            step_cnt      <= 0;")
    a("        end else if (!stall) begin")
    a("            if (s2_valid) begin")
    a("                m_axis_tvalid <= 1'b1;")
    if OW > PE:
        a(f"                m_axis_tdata  <= {{{OW-PE}'d0, cmp_bit}};")
    else:
        a("                m_axis_tdata  <= cmp_bit;")
    a("            end else begin")
    a("                m_axis_tvalid <= 1'b0;")
    a("            end")
    a("            s2_valid <= s1_valid;")
    a("            if (in_fire) begin")
    a("                s1_valid <= 1'b1;")
    a("                if (step_cnt == (OUT_STEPS - 1)) step_cnt <= 0;")
    a("                else                             step_cnt <= step_cnt + 1;")
    a("            end else begin")
    a("                s1_valid <= 1'b0;")
    a("            end")
    a("        end")
    a("    end")
    a("")
    a("endmodule")
    return "\n".join(l) + "\n"



def main():
    for style in ("compact", "tp"):
        for M in (1, 2, 3, 4):
            for n in range(1, 6):
                d = os.path.join(ROOT, "rtl", style, f"m{M}", f"mvau{n}")
                os.makedirs(d, exist_ok=True)
                with open(os.path.join(d, f"MVAU{n}_Super_Wrapper.v"), "w") as f:
                    f.write(gen_wrapper(style, n, M))
                pe = 1 if style == "compact" else PE_TP[n]
                alphas = None
                if style == "tp":
                    alphas = []
                    for b in range(M):
                        with open(os.path.join(ROOT, "sw", "branch_dat",
                                               f"m{M}", f"mvau{n}",
                                               f"alpha_q8_b{b}.txt")) as f:
                            alphas.append(int(f.read().strip()))
                if pe == 1:
                    src = gen_adder_scalar(style, n, M, alphas)
                else:
                    src = gen_adder_pe(n, M, alphas)
                with open(os.path.join(d, f"Stream_Adder_Threshold_mvau{n}.v"), "w") as f:
                    f.write(src)
                print(f"{style} m{M} mvau{n}: wrapper + adder written")
    print("RTL GENERATION DONE ->", os.path.join(ROOT, "rtl"))


if __name__ == "__main__":
    main()
