# ===========================================================================
# [交接導向註解]
# 自動 patch FINN 生成的 MVAU IP（套用本論文對 MVAU 核心/threshold/memstream 的修改）。
# 流程：FINN_Compile 產生 IP 後 → 套用此 patch → RTL/SoC 使用。
# ===========================================================================

#!/usr/bin/env python3
"""
Patch FINN-generated HLS IP RTL to add cfg_wen/cfg_waddr/cfg_wdata write port
to the threshs_ROM modules for MVAU_hls_0 (PE=1, 64x11-bit), MVAU_hls_6 (FC1,
512x8-bit), and MVAU_hls_7 (FC2, 512x10-bit).

For each IP at:
  <FINN_BUILD_DIR>/code_gen_ipgen_<N>/project_<N>/sol1/impl/ip/

Patches:
  1. hdl/verilog/<N>_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R.v
     -> Add cfg ports; replace ROM with writable rom (still initialized from .dat).
  2. hdl/verilog/<N>_Matrix_Vector_Activate_Stream_Batch.v
     -> Add cfg ports cascading down to threshs_U instance.
  3. hdl/verilog/<N>.v (top wrapper)
     -> Add cfg ports cascading to MV module instance.
  4. component.xml
     -> Add port entries for cfg_wen / cfg_waddr / cfg_wdata.

Safe to run multiple times (idempotent).
"""

import os
import re
import shutil

import os, glob as _glob
# FINN 產生碼根目錄:用環境變數指定(每次 build 路徑不同),預設當前目錄下的 finn build tree
FINN_BASE = os.environ.get("FINN_CODEGEN_DIR", "thesis/finn/finn_cifar10")

def _resolve(base_glob):
    """FINN 每次 build 會在 code_gen_ipgen_..._<8字hash> 加不同尾綴;用 wildcard 抓,唯一才回傳。"""
    hits = sorted(_glob.glob(base_glob))
    if len(hits) == 1:
        return hits[0]
    raise SystemExit(f"[patch_finn_ips] 找不到唯一目錄: {base_glob} (命中 {len(hits)} 個);"
                     f"請確認 FINN_CODEGEN_DIR,或該層是否已 ipgen。")

# Per-IP config
IPS = {
    "MVAU_hls_0": dict(
        dir_glob=f"{FINN_BASE}/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_0_*",
        rom_data_width=11,
        rom_addr_width=6,
        rom_depth=64,
        cfg_wdata_width=32,  # write as u32 (use low bits)
    ),
    "MVAU_hls_6": dict(
        dir_glob=f"{FINN_BASE}/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_6_*",
        rom_data_width=8,
        rom_addr_width=9,
        rom_depth=512,
        cfg_wdata_width=32,
    ),
    "MVAU_hls_7": dict(
        dir_glob=f"{FINN_BASE}/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_7_*",
        rom_data_width=10,
        rom_addr_width=9,
        rom_depth=512,
        cfg_wdata_width=32,
    ),
}


def make_rom_v(modname, dat_path, data_width, addr_width, depth, cfg_wdata_width):
    """Build a writable rom Verilog module replacement."""
    return f"""// ==============================================================
// PATCHED: cfg-writable threshs ROM (was read-only) for runtime dataset switch.
// Original auto-generated by Vitis HLS - High-Level Synthesis v2022.2
// ==============================================================
`timescale 1 ns / 1 ps
module {modname} (
    address0, ce0, q0,
    reset, clk,
    cfg_wen, cfg_waddr, cfg_wdata);

parameter DataWidth = {data_width};
parameter AddressWidth = {addr_width};
parameter AddressRange = {depth};

input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

input cfg_wen;
input[AddressWidth-1:0] cfg_waddr;
input[{cfg_wdata_width-1}:0] cfg_wdata;


(* ram_style = "distributed" *) reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
    $readmemh("{dat_path}", rom0);
end


always @(posedge clk)
begin
    if (cfg_wen) begin
        rom0[cfg_waddr] <= cfg_wdata[DataWidth-1:0];
    end
    if (ce0)
    begin
        q0 <= rom0[address0];
    end
end


endmodule
"""


def patch_rom_file(rom_path, modname, dat_path, cfg):
    """Replace the ROM .v file with a cfg-writable version."""
    new_content = make_rom_v(
        modname=modname,
        dat_path=dat_path,
        data_width=cfg["rom_data_width"],
        addr_width=cfg["rom_addr_width"],
        depth=cfg["rom_depth"],
        cfg_wdata_width=cfg["cfg_wdata_width"],
    )
    # backup once
    bak = rom_path + ".pre_cfg_patch.bak"
    if not os.path.exists(bak):
        shutil.copy2(rom_path, bak)
    with open(rom_path, "w") as f:
        f.write(new_content)
    print(f"  patched ROM: {os.path.basename(rom_path)}")


def patch_mv_module(mv_path, cfg):
    """Add cfg ports to Matrix_Vector_Activate_Stream_Batch.v and pass to threshs_U."""
    with open(mv_path, "r") as f:
        src = f.read()
    if "cfg_wen" in src and ".cfg_wen(" in src:
        print(f"  MV module already patched: {os.path.basename(mv_path)}")
        return

    aw = cfg["rom_addr_width"]
    dw = cfg["cfg_wdata_width"]

    # 1. Add cfg_wen, cfg_waddr, cfg_wdata to port list (after last port before closing paren of module decl).
    #    The port list ends with `weights_V_TREADY` (no trailing comma) then `);`
    src = re.sub(
        r"(module \S+ \(\n(?:\s+[^\n]+\n)*?\s+weights_V_TREADY)\s*\n\);",
        r"\1,\n        cfg_wen,\n        cfg_waddr,\n        cfg_wdata\n);",
        src,
        count=1,
    )
    if "cfg_wen" not in src:
        raise RuntimeError(f"port list patch failed for {mv_path}")

    # 2. Add declarations after `output   weights_V_TREADY;`
    src = src.replace(
        "output   weights_V_TREADY;",
        f"output   weights_V_TREADY;\ninput   cfg_wen;\ninput  [{aw-1}:0] cfg_waddr;\ninput  [{dw-1}:0] cfg_wdata;",
        1,
    )

    # 3. Add cfg port mapping to threshs_U instantiation.
    #    The instantiation looks like:
    #       threshs_U(
    #           .clk(ap_clk),
    #           .reset(ap_rst),
    #           .address0(threshs_address0),
    #           .ce0(threshs_ce0),
    #           .q0(threshs_q0)
    #       );
    src = re.sub(
        r"(threshs_U\(.*?\.q0\(threshs_q0\))\s*\n\s*\);",
        r"\1,\n    .cfg_wen(cfg_wen),\n    .cfg_waddr(cfg_waddr),\n    .cfg_wdata(cfg_wdata)\n);",
        src,
        count=1,
        flags=re.DOTALL,
    )
    if ".cfg_wen(cfg_wen)" not in src:
        raise RuntimeError(f"threshs_U inst patch failed for {mv_path}")

    bak = mv_path + ".pre_cfg_patch.bak"
    if not os.path.exists(bak):
        with open(bak, "w") as f:
            f.write(open(mv_path).read())
    with open(mv_path, "w") as f:
        f.write(src)
    print(f"  patched MV module: {os.path.basename(mv_path)}")


def patch_top_module(top_path, cfg):
    """Add cfg ports to MVAU_hls_N.v top wrapper and cascade to inner MV instance."""
    with open(top_path, "r") as f:
        src = f.read()
    if "cfg_wen" in src and ".cfg_wen(cfg_wen)" in src:
        print(f"  Top module already patched: {os.path.basename(top_path)}")
        return

    aw = cfg["rom_addr_width"]
    dw = cfg["cfg_wdata_width"]

    # 1. Add cfg ports to module port list: ends with `out_V_TREADY` then `);`
    src = re.sub(
        r"(module \S+ \(\n(?:\s+[^\n]+\n)*?\s+out_V_TREADY)\s*\n\);",
        r"\1,\n        cfg_wen,\n        cfg_waddr,\n        cfg_wdata\n);",
        src,
        count=1,
    )
    if "cfg_wen" not in src:
        raise RuntimeError(f"top port list patch failed for {top_path}")

    # 2. Add declarations after `input   out_V_TREADY;`
    src = src.replace(
        "input   out_V_TREADY;",
        f"input   out_V_TREADY;\ninput   cfg_wen;\ninput  [{aw-1}:0] cfg_waddr;\ninput  [{dw-1}:0] cfg_wdata;",
        1,
    )

    # 3. Find the grp_Matrix_Vector_Activate_Stream_Batch_fu_<N> instance and append cfg mapping.
    src = re.sub(
        r"(grp_Matrix_Vector_Activate_Stream_Batch_fu_\d+\(.*?\.weights_V_TREADY\(grp_Matrix_Vector_Activate_Stream_Batch_fu_\d+_weights_V_TREADY\))\s*\n\);",
        r"\1,\n    .cfg_wen(cfg_wen),\n    .cfg_waddr(cfg_waddr),\n    .cfg_wdata(cfg_wdata)\n);",
        src,
        count=1,
        flags=re.DOTALL,
    )
    if ".cfg_wen(cfg_wen)" not in src:
        raise RuntimeError(f"MV inst patch failed in {top_path}")

    bak = top_path + ".pre_cfg_patch.bak"
    if not os.path.exists(bak):
        with open(bak, "w") as f:
            f.write(open(top_path).read())
    with open(top_path, "w") as f:
        f.write(src)
    print(f"  patched top module: {os.path.basename(top_path)}")


def patch_component_xml(xml_path, cfg):
    """Add cfg_wen / cfg_waddr / cfg_wdata <spirit:port> entries to component.xml.
    Inserts right before the closing </spirit:ports>."""
    with open(xml_path, "r") as f:
        src = f.read()
    if "<spirit:name>cfg_wen</spirit:name>" in src:
        print(f"  component.xml already patched: {os.path.basename(xml_path)}")
        return

    aw = cfg["rom_addr_width"]
    dw = cfg["cfg_wdata_width"]

    new_ports = f"""      <spirit:port>
        <spirit:name>cfg_wen</spirit:name>
        <spirit:wire>
          <spirit:direction>in</spirit:direction>
          <spirit:wireTypeDefs>
            <spirit:wireTypeDef>
              <spirit:typeName>std_logic</spirit:typeName>
              <spirit:viewNameRef>xilinx_verilogsynthesis</spirit:viewNameRef>
              <spirit:viewNameRef>xilinx_verilogbehavioralsimulation</spirit:viewNameRef>
            </spirit:wireTypeDef>
          </spirit:wireTypeDefs>
        </spirit:wire>
      </spirit:port>
      <spirit:port>
        <spirit:name>cfg_waddr</spirit:name>
        <spirit:wire>
          <spirit:direction>in</spirit:direction>
          <spirit:vector>
            <spirit:left spirit:format="long">{aw-1}</spirit:left>
            <spirit:right spirit:format="long">0</spirit:right>
          </spirit:vector>
          <spirit:wireTypeDefs>
            <spirit:wireTypeDef>
              <spirit:typeName>std_logic_vector</spirit:typeName>
              <spirit:viewNameRef>xilinx_verilogsynthesis</spirit:viewNameRef>
              <spirit:viewNameRef>xilinx_verilogbehavioralsimulation</spirit:viewNameRef>
            </spirit:wireTypeDef>
          </spirit:wireTypeDefs>
        </spirit:wire>
      </spirit:port>
      <spirit:port>
        <spirit:name>cfg_wdata</spirit:name>
        <spirit:wire>
          <spirit:direction>in</spirit:direction>
          <spirit:vector>
            <spirit:left spirit:format="long">{dw-1}</spirit:left>
            <spirit:right spirit:format="long">0</spirit:right>
          </spirit:vector>
          <spirit:wireTypeDefs>
            <spirit:wireTypeDef>
              <spirit:typeName>std_logic_vector</spirit:typeName>
              <spirit:viewNameRef>xilinx_verilogsynthesis</spirit:viewNameRef>
              <spirit:viewNameRef>xilinx_verilogbehavioralsimulation</spirit:viewNameRef>
            </spirit:wireTypeDef>
          </spirit:wireTypeDefs>
        </spirit:wire>
      </spirit:port>
    </spirit:ports>"""

    if "</spirit:ports>" not in src:
        raise RuntimeError(f"no </spirit:ports> tag in {xml_path}")
    src = src.replace("    </spirit:ports>", new_ports, 1)

    bak = xml_path + ".pre_cfg_patch.bak"
    if not os.path.exists(bak):
        with open(bak, "w") as f:
            f.write(open(xml_path).read())
    with open(xml_path, "w") as f:
        f.write(src)
    print(f"  patched component.xml: {os.path.basename(xml_path)}")


def patch_one_ip(name, cfg):
    base = _resolve(cfg["dir_glob"])
    print(f"\n=== {name}: {base} ===")
    # Find HLS verilog dir
    ip_dir = os.path.join(
        base,
        f"project_StreamingDataflowPartition_1_{name}",
        "sol1",
        "impl",
        "ip",
    )
    rtl_dir = os.path.join(ip_dir, "hdl", "verilog")
    if not os.path.isdir(rtl_dir):
        raise RuntimeError(f"not found: {rtl_dir}")

    rom_v = os.path.join(
        rtl_dir,
        f"StreamingDataflowPartition_1_{name}_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R.v",
    )
    rom_dat = os.path.join(
        rtl_dir,
        f"StreamingDataflowPartition_1_{name}_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R.dat",
    )
    mv_v = os.path.join(
        rtl_dir,
        f"StreamingDataflowPartition_1_{name}_Matrix_Vector_Activate_Stream_Batch.v",
    )
    top_v = os.path.join(rtl_dir, f"StreamingDataflowPartition_1_{name}.v")
    xml = os.path.join(ip_dir, "component.xml")

    assert os.path.exists(rom_v), rom_v
    assert os.path.exists(rom_dat), rom_dat
    assert os.path.exists(mv_v), mv_v
    assert os.path.exists(top_v), top_v
    assert os.path.exists(xml), xml

    patch_rom_file(
        rom_v,
        modname=f"StreamingDataflowPartition_1_{name}_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R",
        dat_path=rom_dat,
        cfg=cfg,
    )
    patch_mv_module(mv_v, cfg)
    patch_top_module(top_v, cfg)
    patch_component_xml(xml, cfg)


if __name__ == "__main__":
    for name, cfg in IPS.items():
        patch_one_ip(name, cfg)
    print("\nAll FINN IPs patched.")
