// ===========================================================================
// [交接導向註解]
// MVAU6 Matrix-Vector-Activate（MAC 核心）— FC1 — threshold ROM 變 cfg 可寫
// 
// 改動明細（patch_finn_ips.py）：
//  1. module 埠新增：input cfg_wen; input [8:0] cfg_waddr; input [31:0] cfg_wdata;（512-deep）
//  2. threshs_U 實例新增 .cfg_wen/.cfg_waddr/.cfg_wdata 接線
// 
// 流程：FINN 生成 → 本論文修改此檔 → RTL/super_wrapper 整合 → SoC → FPGA。
// ===========================================================================

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingDataflowPartition_1_MVAU_hls_6_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY,
        cfg_wen,
        cfg_waddr,
        cfg_wdata
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input  [7:0] weights_V_TDATA;
output   weights_V_TREADY;
input   cfg_wen;
input  [8:0] cfg_waddr;
input  [31:0] cfg_wdata;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] icmp_ln249_fu_649_p2;
wire   [0:0] icmp_ln253_fu_661_p2;
reg    ap_predicate_op159_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_2048;
reg   [0:0] icmp_ln249_reg_2048_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_2085;
reg   [0:0] icmp_ln290_reg_2085_pp0_iter1_reg;
reg    ap_predicate_op342_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] threshs_address0;
reg    threshs_ce0;
wire   [7:0] threshs_q0;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [31:0] nf_2_reg_2043;
wire   [0:0] icmp_ln249_reg_2048_pp0_iter0_reg;
wire   [5:0] trunc_ln257_fu_1066_p1;
wire   [0:0] icmp_ln272_fu_1394_p2;
reg   [0:0] icmp_ln272_reg_2060;
wire   [0:0] r_fu_1434_p2;
reg   [0:0] r_reg_2065;
wire   [0:0] r_1_fu_1454_p2;
reg   [0:0] r_1_reg_2070;
wire   [0:0] r_2_fu_1474_p2;
reg   [0:0] r_2_reg_2075;
wire   [0:0] r_3_fu_1494_p2;
reg   [0:0] r_3_reg_2080;
wire   [0:0] icmp_ln290_fu_1506_p2;
wire   [31:0] add_ln840_3_fu_1596_p2;
reg   [31:0] add_ln840_3_reg_2089;
reg   [3:0] ap_phi_mux_inElem_1_phi_fu_493_p130;
wire   [3:0] inElem_fu_998_p1;
wire   [3:0] ap_phi_reg_pp0_iter0_inElem_1_reg_490;
wire   [3:0] tmp_fu_863_p66;
wire   [63:0] idxprom2_i_fu_1602_p1;
reg   [31:0] sf_fu_186;
wire   [31:0] sf_2_fu_1500_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [15:0] i_fu_190;
wire   [15:0] i_2_fu_655_p2;
reg   [15:0] ap_sig_allocacmp_i_1;
reg   [31:0] add_i_i_i_334_fu_194;
reg   [3:0] inputBuf_V_fu_198;
reg   [3:0] inputBuf_V_1_fu_202;
reg   [3:0] inputBuf_V_2_fu_206;
reg   [3:0] inputBuf_V_3_fu_210;
reg   [3:0] inputBuf_V_4_fu_214;
reg   [3:0] inputBuf_V_5_fu_218;
reg   [3:0] inputBuf_V_6_fu_222;
reg   [3:0] inputBuf_V_7_fu_226;
reg   [3:0] inputBuf_V_8_fu_230;
reg   [3:0] inputBuf_V_9_fu_234;
reg   [3:0] inputBuf_V_10_fu_238;
reg   [3:0] inputBuf_V_11_fu_242;
reg   [3:0] inputBuf_V_12_fu_246;
reg   [3:0] inputBuf_V_13_fu_250;
reg   [3:0] inputBuf_V_14_fu_254;
reg   [3:0] inputBuf_V_15_fu_258;
reg   [3:0] inputBuf_V_16_fu_262;
reg   [3:0] inputBuf_V_17_fu_266;
reg   [3:0] inputBuf_V_18_fu_270;
reg   [3:0] inputBuf_V_19_fu_274;
reg   [3:0] inputBuf_V_20_fu_278;
reg   [3:0] inputBuf_V_21_fu_282;
reg   [3:0] inputBuf_V_22_fu_286;
reg   [3:0] inputBuf_V_23_fu_290;
reg   [3:0] inputBuf_V_24_fu_294;
reg   [3:0] inputBuf_V_25_fu_298;
reg   [3:0] inputBuf_V_26_fu_302;
reg   [3:0] inputBuf_V_27_fu_306;
reg   [3:0] inputBuf_V_28_fu_310;
reg   [3:0] inputBuf_V_29_fu_314;
reg   [3:0] inputBuf_V_30_fu_318;
reg   [3:0] inputBuf_V_31_fu_322;
reg   [3:0] inputBuf_V_32_fu_326;
reg   [3:0] inputBuf_V_33_fu_330;
reg   [3:0] inputBuf_V_34_fu_334;
reg   [3:0] inputBuf_V_35_fu_338;
reg   [3:0] inputBuf_V_36_fu_342;
reg   [3:0] inputBuf_V_37_fu_346;
reg   [3:0] inputBuf_V_38_fu_350;
reg   [3:0] inputBuf_V_39_fu_354;
reg   [3:0] inputBuf_V_40_fu_358;
reg   [3:0] inputBuf_V_41_fu_362;
reg   [3:0] inputBuf_V_42_fu_366;
reg   [3:0] inputBuf_V_43_fu_370;
reg   [3:0] inputBuf_V_44_fu_374;
reg   [3:0] inputBuf_V_45_fu_378;
reg   [3:0] inputBuf_V_46_fu_382;
reg   [3:0] inputBuf_V_47_fu_386;
reg   [3:0] inputBuf_V_48_fu_390;
reg   [3:0] inputBuf_V_49_fu_394;
reg   [3:0] inputBuf_V_50_fu_398;
reg   [3:0] inputBuf_V_51_fu_402;
reg   [3:0] inputBuf_V_52_fu_406;
reg   [3:0] inputBuf_V_53_fu_410;
reg   [3:0] inputBuf_V_54_fu_414;
reg   [3:0] inputBuf_V_55_fu_418;
reg   [3:0] inputBuf_V_56_fu_422;
reg   [3:0] inputBuf_V_57_fu_426;
reg   [3:0] inputBuf_V_58_fu_430;
reg   [3:0] inputBuf_V_59_fu_434;
reg   [3:0] inputBuf_V_60_fu_438;
reg   [3:0] inputBuf_V_61_fu_442;
reg   [3:0] inputBuf_V_62_fu_446;
reg   [3:0] inputBuf_V_63_fu_450;
reg   [31:0] nf_1_fu_454;
wire   [31:0] nf_3_fu_1529_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [5:0] tmp_fu_863_p65;
wire   [0:0] local_temp_V_fu_1400_p1;
wire   [0:0] xor_ln1019_fu_1428_p2;
wire   [0:0] p_Result_s_fu_1390_p1;
wire   [0:0] p_Result_1_fu_1440_p3;
wire   [0:0] local_temp_V_1_fu_1404_p3;
wire   [0:0] xor_ln1019_2_fu_1448_p2;
wire   [0:0] local_temp_V_2_fu_1412_p3;
wire   [0:0] xor_ln1019_4_fu_1468_p2;
wire   [0:0] p_Result_2_fu_1460_p3;
wire   [0:0] local_temp_V_3_fu_1420_p3;
wire   [0:0] xor_ln1019_6_fu_1488_p2;
wire   [0:0] p_Result_3_fu_1480_p3;
wire   [31:0] nf_fu_1517_p2;
wire   [0:0] icmp_ln302_fu_1523_p2;
wire   [31:0] select_ln272_fu_1555_p3;
wire   [31:0] zext_ln68_fu_1565_p1;
wire   [1:0] zext_ln90_1_fu_1568_p1;
wire   [1:0] zext_ln90_2_fu_1571_p1;
wire   [1:0] add_ln840_1_fu_1580_p2;
wire   [1:0] zext_ln90_fu_1562_p1;
wire   [1:0] add_ln840_2_fu_1586_p2;
wire   [31:0] zext_ln840_fu_1592_p1;
wire   [31:0] add_ln840_fu_1574_p2;
wire   [31:0] zext_ln1039_fu_1611_p1;
wire   [0:0] icmp_ln1039_fu_1615_p2;
wire   [0:0] result_V_fu_1620_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
reg    ap_condition_1136;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

StreamingDataflowPartition_1_MVAU_hls_6_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
threshs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_address0),
    .ce0(threshs_ce0),
    .q0(threshs_q0),
    .cfg_wen(cfg_wen),
    .cfg_waddr(cfg_waddr),
    .cfg_wdata(cfg_wdata)
);

StreamingDataflowPartition_1_MVAU_hls_6_mux_646_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 4 ),
    .din5_WIDTH( 4 ),
    .din6_WIDTH( 4 ),
    .din7_WIDTH( 4 ),
    .din8_WIDTH( 4 ),
    .din9_WIDTH( 4 ),
    .din10_WIDTH( 4 ),
    .din11_WIDTH( 4 ),
    .din12_WIDTH( 4 ),
    .din13_WIDTH( 4 ),
    .din14_WIDTH( 4 ),
    .din15_WIDTH( 4 ),
    .din16_WIDTH( 4 ),
    .din17_WIDTH( 4 ),
    .din18_WIDTH( 4 ),
    .din19_WIDTH( 4 ),
    .din20_WIDTH( 4 ),
    .din21_WIDTH( 4 ),
    .din22_WIDTH( 4 ),
    .din23_WIDTH( 4 ),
    .din24_WIDTH( 4 ),
    .din25_WIDTH( 4 ),
    .din26_WIDTH( 4 ),
    .din27_WIDTH( 4 ),
    .din28_WIDTH( 4 ),
    .din29_WIDTH( 4 ),
    .din30_WIDTH( 4 ),
    .din31_WIDTH( 4 ),
    .din32_WIDTH( 4 ),
    .din33_WIDTH( 4 ),
    .din34_WIDTH( 4 ),
    .din35_WIDTH( 4 ),
    .din36_WIDTH( 4 ),
    .din37_WIDTH( 4 ),
    .din38_WIDTH( 4 ),
    .din39_WIDTH( 4 ),
    .din40_WIDTH( 4 ),
    .din41_WIDTH( 4 ),
    .din42_WIDTH( 4 ),
    .din43_WIDTH( 4 ),
    .din44_WIDTH( 4 ),
    .din45_WIDTH( 4 ),
    .din46_WIDTH( 4 ),
    .din47_WIDTH( 4 ),
    .din48_WIDTH( 4 ),
    .din49_WIDTH( 4 ),
    .din50_WIDTH( 4 ),
    .din51_WIDTH( 4 ),
    .din52_WIDTH( 4 ),
    .din53_WIDTH( 4 ),
    .din54_WIDTH( 4 ),
    .din55_WIDTH( 4 ),
    .din56_WIDTH( 4 ),
    .din57_WIDTH( 4 ),
    .din58_WIDTH( 4 ),
    .din59_WIDTH( 4 ),
    .din60_WIDTH( 4 ),
    .din61_WIDTH( 4 ),
    .din62_WIDTH( 4 ),
    .din63_WIDTH( 4 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 4 ))
mux_646_4_1_1_U1(
    .din0(inputBuf_V_fu_198),
    .din1(inputBuf_V_1_fu_202),
    .din2(inputBuf_V_2_fu_206),
    .din3(inputBuf_V_3_fu_210),
    .din4(inputBuf_V_4_fu_214),
    .din5(inputBuf_V_5_fu_218),
    .din6(inputBuf_V_6_fu_222),
    .din7(inputBuf_V_7_fu_226),
    .din8(inputBuf_V_8_fu_230),
    .din9(inputBuf_V_9_fu_234),
    .din10(inputBuf_V_10_fu_238),
    .din11(inputBuf_V_11_fu_242),
    .din12(inputBuf_V_12_fu_246),
    .din13(inputBuf_V_13_fu_250),
    .din14(inputBuf_V_14_fu_254),
    .din15(inputBuf_V_15_fu_258),
    .din16(inputBuf_V_16_fu_262),
    .din17(inputBuf_V_17_fu_266),
    .din18(inputBuf_V_18_fu_270),
    .din19(inputBuf_V_19_fu_274),
    .din20(inputBuf_V_20_fu_278),
    .din21(inputBuf_V_21_fu_282),
    .din22(inputBuf_V_22_fu_286),
    .din23(inputBuf_V_23_fu_290),
    .din24(inputBuf_V_24_fu_294),
    .din25(inputBuf_V_25_fu_298),
    .din26(inputBuf_V_26_fu_302),
    .din27(inputBuf_V_27_fu_306),
    .din28(inputBuf_V_28_fu_310),
    .din29(inputBuf_V_29_fu_314),
    .din30(inputBuf_V_30_fu_318),
    .din31(inputBuf_V_31_fu_322),
    .din32(inputBuf_V_32_fu_326),
    .din33(inputBuf_V_33_fu_330),
    .din34(inputBuf_V_34_fu_334),
    .din35(inputBuf_V_35_fu_338),
    .din36(inputBuf_V_36_fu_342),
    .din37(inputBuf_V_37_fu_346),
    .din38(inputBuf_V_38_fu_350),
    .din39(inputBuf_V_39_fu_354),
    .din40(inputBuf_V_40_fu_358),
    .din41(inputBuf_V_41_fu_362),
    .din42(inputBuf_V_42_fu_366),
    .din43(inputBuf_V_43_fu_370),
    .din44(inputBuf_V_44_fu_374),
    .din45(inputBuf_V_45_fu_378),
    .din46(inputBuf_V_46_fu_382),
    .din47(inputBuf_V_47_fu_386),
    .din48(inputBuf_V_48_fu_390),
    .din49(inputBuf_V_49_fu_394),
    .din50(inputBuf_V_50_fu_398),
    .din51(inputBuf_V_51_fu_402),
    .din52(inputBuf_V_52_fu_406),
    .din53(inputBuf_V_53_fu_410),
    .din54(inputBuf_V_54_fu_414),
    .din55(inputBuf_V_55_fu_418),
    .din56(inputBuf_V_56_fu_422),
    .din57(inputBuf_V_57_fu_426),
    .din58(inputBuf_V_58_fu_430),
    .din59(inputBuf_V_59_fu_434),
    .din60(inputBuf_V_60_fu_438),
    .din61(inputBuf_V_61_fu_442),
    .din62(inputBuf_V_62_fu_446),
    .din63(inputBuf_V_63_fu_450),
    .din64(tmp_fu_863_p65),
    .dout(tmp_fu_863_p66)
);

StreamingDataflowPartition_1_MVAU_hls_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1136)) begin
        if ((icmp_ln249_fu_649_p2 == 1'd0)) begin
            i_fu_190 <= i_2_fu_655_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_190 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1136)) begin
        if (((icmp_ln249_fu_649_p2 == 1'd0) & (icmp_ln290_fu_1506_p2 == 1'd1))) begin
            nf_1_fu_454 <= nf_3_fu_1529_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_1_fu_454 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1136)) begin
        if (((icmp_ln249_fu_649_p2 == 1'd0) & (icmp_ln290_fu_1506_p2 == 1'd1))) begin
            sf_fu_186 <= 32'd0;
        end else if (((icmp_ln249_fu_649_p2 == 1'd0) & (icmp_ln290_fu_1506_p2 == 1'd0))) begin
            sf_fu_186 <= sf_2_fu_1500_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_186 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (icmp_ln249_reg_2048_pp0_iter0_reg == 1'd0))) begin
        add_i_i_i_334_fu_194 <= add_ln840_3_fu_1596_p2;
        add_ln840_3_reg_2089 <= add_ln840_3_fu_1596_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_2048 <= icmp_ln249_fu_649_p2;
        nf_2_reg_2043 <= ap_sig_allocacmp_nf_2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln249_reg_2048_pp0_iter1_reg <= icmp_ln249_reg_2048;
        icmp_ln290_reg_2085_pp0_iter1_reg <= icmp_ln290_reg_2085;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln272_reg_2060 <= icmp_ln272_fu_1394_p2;
        icmp_ln290_reg_2085 <= icmp_ln290_fu_1506_p2;
        r_1_reg_2070 <= r_1_fu_1454_p2;
        r_2_reg_2075 <= r_2_fu_1474_p2;
        r_3_reg_2080 <= r_3_fu_1494_p2;
        r_reg_2065 <= r_fu_1434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd10))) begin
        inputBuf_V_10_fu_238 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd11))) begin
        inputBuf_V_11_fu_242 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd12))) begin
        inputBuf_V_12_fu_246 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd13))) begin
        inputBuf_V_13_fu_250 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd14))) begin
        inputBuf_V_14_fu_254 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd15))) begin
        inputBuf_V_15_fu_258 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd16))) begin
        inputBuf_V_16_fu_262 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd17))) begin
        inputBuf_V_17_fu_266 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd18))) begin
        inputBuf_V_18_fu_270 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd19))) begin
        inputBuf_V_19_fu_274 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd1))) begin
        inputBuf_V_1_fu_202 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd20))) begin
        inputBuf_V_20_fu_278 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd21))) begin
        inputBuf_V_21_fu_282 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd22))) begin
        inputBuf_V_22_fu_286 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd23))) begin
        inputBuf_V_23_fu_290 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd24))) begin
        inputBuf_V_24_fu_294 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd25))) begin
        inputBuf_V_25_fu_298 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd26))) begin
        inputBuf_V_26_fu_302 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd27))) begin
        inputBuf_V_27_fu_306 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd28))) begin
        inputBuf_V_28_fu_310 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd29))) begin
        inputBuf_V_29_fu_314 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd2))) begin
        inputBuf_V_2_fu_206 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd30))) begin
        inputBuf_V_30_fu_318 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd31))) begin
        inputBuf_V_31_fu_322 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd32))) begin
        inputBuf_V_32_fu_326 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd33))) begin
        inputBuf_V_33_fu_330 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd34))) begin
        inputBuf_V_34_fu_334 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd35))) begin
        inputBuf_V_35_fu_338 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd36))) begin
        inputBuf_V_36_fu_342 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd37))) begin
        inputBuf_V_37_fu_346 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd38))) begin
        inputBuf_V_38_fu_350 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd39))) begin
        inputBuf_V_39_fu_354 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd3))) begin
        inputBuf_V_3_fu_210 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd40))) begin
        inputBuf_V_40_fu_358 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd41))) begin
        inputBuf_V_41_fu_362 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd42))) begin
        inputBuf_V_42_fu_366 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd43))) begin
        inputBuf_V_43_fu_370 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd44))) begin
        inputBuf_V_44_fu_374 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd45))) begin
        inputBuf_V_45_fu_378 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd46))) begin
        inputBuf_V_46_fu_382 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd47))) begin
        inputBuf_V_47_fu_386 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd48))) begin
        inputBuf_V_48_fu_390 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd49))) begin
        inputBuf_V_49_fu_394 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd4))) begin
        inputBuf_V_4_fu_214 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd50))) begin
        inputBuf_V_50_fu_398 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd51))) begin
        inputBuf_V_51_fu_402 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd52))) begin
        inputBuf_V_52_fu_406 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd53))) begin
        inputBuf_V_53_fu_410 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd54))) begin
        inputBuf_V_54_fu_414 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd55))) begin
        inputBuf_V_55_fu_418 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd56))) begin
        inputBuf_V_56_fu_422 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd57))) begin
        inputBuf_V_57_fu_426 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd58))) begin
        inputBuf_V_58_fu_430 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd59))) begin
        inputBuf_V_59_fu_434 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd5))) begin
        inputBuf_V_5_fu_218 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd60))) begin
        inputBuf_V_60_fu_438 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd61))) begin
        inputBuf_V_61_fu_442 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd62))) begin
        inputBuf_V_62_fu_446 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd63))) begin
        inputBuf_V_63_fu_450 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd6))) begin
        inputBuf_V_6_fu_222 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd7))) begin
        inputBuf_V_7_fu_226 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd8))) begin
        inputBuf_V_8_fu_230 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd9))) begin
        inputBuf_V_9_fu_234 <= inElem_fu_998_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (trunc_ln257_fu_1066_p1 == 6'd0))) begin
        inputBuf_V_fu_198 <= inElem_fu_998_p1;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_649_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_661_p2 == 1'd0) & (icmp_ln249_fu_649_p2 == 1'd0))) begin
        ap_phi_mux_inElem_1_phi_fu_493_p130 = tmp_fu_863_p66;
    end else if ((((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd62)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd0)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd1)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd2)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd3)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd4)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd5)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd6)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd7)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd8)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd9)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd10)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd11)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd12)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd13)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd14)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd15)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd16)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd17)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd18)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd19)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd20)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd21)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd22)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd23)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd24)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd25)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd26)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd27)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd28)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd29)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd30)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd31)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd32)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd33)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd34)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd35)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd36)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd37)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd38)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd39)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd40)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd41)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd42)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd43)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd44)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd45)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd46)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd47)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd48)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd49)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd50)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd51)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd52)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd53)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd54)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd55)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd56)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd57)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd58)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd59)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd60)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd61)) | ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0) & (trunc_ln257_fu_1066_p1 == 6'd63)))) begin
        ap_phi_mux_inElem_1_phi_fu_493_p130 = inElem_fu_998_p1;
    end else begin
        ap_phi_mux_inElem_1_phi_fu_493_p130 = ap_phi_reg_pp0_iter0_inElem_1_reg_490;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 16'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_190;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_1_fu_454;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_186;
    end
end

always @ (*) begin
    if (((ap_predicate_op159_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (ap_predicate_op159_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op342_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (ap_predicate_op342_write_state3 == 1'b1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        threshs_ce0 = 1'b1;
    end else begin
        threshs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (icmp_ln249_fu_649_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ~((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if (((~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0))) & (icmp_ln249_reg_2048_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln840_1_fu_1580_p2 = (zext_ln90_1_fu_1568_p1 + zext_ln90_2_fu_1571_p1);

assign add_ln840_2_fu_1586_p2 = (add_ln840_1_fu_1580_p2 + zext_ln90_fu_1562_p1);

assign add_ln840_3_fu_1596_p2 = (zext_ln840_fu_1592_p1 + add_ln840_fu_1574_p2);

assign add_ln840_fu_1574_p2 = (select_ln272_fu_1555_p3 + zext_ln68_fu_1565_p1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_1136 = (~((ap_start_int == 1'b0) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op342_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_649_p2 == 1'd0)) | ((ap_predicate_op159_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_1_reg_490 = 'bx;

always @ (*) begin
    ap_predicate_op159_read_state1 = ((icmp_ln253_fu_661_p2 == 1'd1) & (icmp_ln249_fu_649_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op342_write_state3 = ((icmp_ln290_reg_2085_pp0_iter1_reg == 1'd1) & (icmp_ln249_reg_2048_pp0_iter1_reg == 1'd0));
end

assign i_2_fu_655_p2 = (ap_sig_allocacmp_i_1 + 16'd1);

assign icmp_ln1039_fu_1615_p2 = (($signed(add_ln840_3_reg_2089) < $signed(zext_ln1039_fu_1611_p1)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_649_p2 = ((ap_sig_allocacmp_i_1 == 16'd32768) ? 1'b1 : 1'b0);

assign icmp_ln249_reg_2048_pp0_iter0_reg = icmp_ln249_reg_2048;

assign icmp_ln253_fu_661_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_1394_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_1506_p2 = ((sf_2_fu_1500_p2 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_1523_p2 = ((nf_fu_1517_p2 == 32'd512) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_1602_p1 = nf_2_reg_2043;

assign inElem_fu_998_p1 = in0_V_TDATA[3:0];

assign local_temp_V_1_fu_1404_p3 = weights_V_TDATA[32'd1];

assign local_temp_V_2_fu_1412_p3 = weights_V_TDATA[32'd2];

assign local_temp_V_3_fu_1420_p3 = weights_V_TDATA[32'd3];

assign local_temp_V_fu_1400_p1 = weights_V_TDATA[0:0];

assign nf_3_fu_1529_p3 = ((icmp_ln302_fu_1523_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_1517_p2);

assign nf_fu_1517_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign out_V_TDATA = result_V_fu_1620_p2;

assign p_Result_1_fu_1440_p3 = ap_phi_mux_inElem_1_phi_fu_493_p130[32'd1];

assign p_Result_2_fu_1460_p3 = ap_phi_mux_inElem_1_phi_fu_493_p130[32'd2];

assign p_Result_3_fu_1480_p3 = ap_phi_mux_inElem_1_phi_fu_493_p130[32'd3];

assign p_Result_s_fu_1390_p1 = ap_phi_mux_inElem_1_phi_fu_493_p130[0:0];

assign r_1_fu_1454_p2 = (xor_ln1019_2_fu_1448_p2 ^ 1'd1);

assign r_2_fu_1474_p2 = (xor_ln1019_4_fu_1468_p2 ^ p_Result_2_fu_1460_p3);

assign r_3_fu_1494_p2 = (xor_ln1019_6_fu_1488_p2 ^ p_Result_3_fu_1480_p3);

assign r_fu_1434_p2 = (xor_ln1019_fu_1428_p2 ^ p_Result_s_fu_1390_p1);

assign result_V_fu_1620_p2 = (icmp_ln1039_fu_1615_p2 ^ 1'd1);

assign select_ln272_fu_1555_p3 = ((icmp_ln272_reg_2060[0:0] == 1'b1) ? 32'd0 : add_i_i_i_334_fu_194);

assign sf_2_fu_1500_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign threshs_address0 = idxprom2_i_fu_1602_p1;

assign tmp_fu_863_p65 = ap_sig_allocacmp_sf_1[5:0];

assign trunc_ln257_fu_1066_p1 = ap_sig_allocacmp_sf_1[5:0];

assign xor_ln1019_2_fu_1448_p2 = (p_Result_1_fu_1440_p3 ^ local_temp_V_1_fu_1404_p3);

assign xor_ln1019_4_fu_1468_p2 = (local_temp_V_2_fu_1412_p3 ^ 1'd1);

assign xor_ln1019_6_fu_1488_p2 = (local_temp_V_3_fu_1420_p3 ^ 1'd1);

assign xor_ln1019_fu_1428_p2 = (local_temp_V_fu_1400_p1 ^ 1'd1);

assign zext_ln1039_fu_1611_p1 = threshs_q0;

assign zext_ln68_fu_1565_p1 = r_1_reg_2070;

assign zext_ln840_fu_1592_p1 = add_ln840_2_fu_1586_p2;

assign zext_ln90_1_fu_1568_p1 = r_2_reg_2075;

assign zext_ln90_2_fu_1571_p1 = r_3_reg_2080;

assign zext_ln90_fu_1562_p1 = r_reg_2065;

endmodule //StreamingDataflowPartition_1_MVAU_hls_6_Matrix_Vector_Activate_Stream_Batch
