// ===========================================================================
// [交接導向註解]
// MVAU6 — FC1（全連接，MVAU_hls_6）
// 改造：threshs_ROM 由唯讀改為 cfg-可寫（512×8-bit）。
// 
// 本檔：
//   ★ 本檔為『改過』的關鍵檔（patch_finn_ips.py）：
//     原 FINN 自動生成之唯讀 ROM → 加入 cfg_wen / cfg_waddr / cfg_wdata 埠變為可寫；
//     仍由 .dat 經 $readmemh 初始化，cfg_wen=1 時將 cfg_wdata 寫入 rom0[cfg_waddr]。
//     → 這就是 runtime 換任務能改 threshold 而不重燒 bitstream 的機制。
// 
// 流程：FINN_Compile 產生 → 本論文修改 → RTL/super_wrapper 整合 → SoC 縫合 → FPGA。
// ===========================================================================

// ==============================================================
// PATCHED: cfg-writable threshs ROM (was read-only) for runtime dataset switch.
// Original auto-generated by Vitis HLS - High-Level Synthesis v2022.2
// ==============================================================
`timescale 1 ns / 1 ps
module StreamingDataflowPartition_1_MVAU_hls_6_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R (
    address0, ce0, q0,
    reset, clk,
    cfg_wen, cfg_waddr, cfg_wdata);

parameter DataWidth = 8;
parameter AddressWidth = 9;
parameter AddressRange = 512;

input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

input cfg_wen;
input[AddressWidth-1:0] cfg_waddr;
input[31:0] cfg_wdata;


(* ram_style = "distributed" *) reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
    $readmemh("/home/barkie1/thesis/finn/finn_cifar10/code_gen_ipgen_StreamingDataflowPartition_1_MVAU_hls_6_uplvgsm4/project_StreamingDataflowPartition_1_MVAU_hls_6/sol1/impl/ip/hdl/verilog/StreamingDataflowPartition_1_MVAU_hls_6_Matrix_Vector_Activate_Stream_Batch_threshs_ROM_AUTO_1R.dat", rom0);
end


always @(posedge clk)
begin
    if (cfg_wen) begin
        rom0[cfg_waddr] <= cfg_wdata[DataWidth-1:0];
    end
    if (ce0)
    begin
        q0 <= rom0[address0];
    end
end


endmodule
